import { expect, test } from '@playwright/test'

async function enterDemo(page: import('@playwright/test').Page){await page.goto('/');await page.getByRole('button',{name:/explore the interactive demo/i}).click();await expect(page.getByRole('heading',{name:/today, clearly/i})).toBeVisible()}

test('authentication page is safe with or without local Supabase variables',async({page})=>{await page.goto('/');await expect(page.locator('.brand-mark').first()).toBeVisible();if(await page.getByText(/supabase setup needed/i).isVisible())await expect(page.getByRole('button',{name:/explore the interactive demo/i})).toBeVisible();else{await expect(page.getByRole('tab',{name:'Sign in'})).toHaveAttribute('aria-selected','true');await expect(page.getByLabel('Password',{exact:true})).toBeVisible();await page.getByRole('tab',{name:'Create account'}).click();await expect(page.getByLabel('Confirm password')).toBeVisible()}})

test('V2 primary navigation is Today, Train, Study, Life and Progress',async({page})=>{await enterDemo(page);for(const name of ['Today','Train','Study','Life','Progress'])await expect(page.getByRole('link',{name:new RegExp(name,'i')}).first()).toBeVisible();await expect(page.getByRole('link',{name:/food/i})).toHaveCount(0)})

test('Today controls stay readable, grouped and touch-friendly',async({page},testInfo)=>{await enterDemo(page);const previous=page.getByRole('button',{name:'Previous week'});const next=page.getByRole('button',{name:'Next week'});for(const control of [previous,next,page.getByRole('button',{name:'Nutrition',exact:true}),page.getByRole('button',{name:'Health',exact:true})]){const box=await control.boundingBox();expect(box?.height).toBeGreaterThanOrEqual(44)}await expect(page.locator('.focus-card .badge')).toHaveCount(0);const noteSize=await page.locator('.week-context-note').evaluate((element)=>Number.parseFloat(getComputedStyle(element).fontSize));expect(noteSize).toBeGreaterThanOrEqual(12);const previousBorder=await previous.evaluate((element)=>getComputedStyle(element).borderTopWidth);expect(previousBorder).not.toBe('0px');const hasHorizontalOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);expect(hasHorizontalOverflow).toBe(false);if(testInfo.project.name==='desktop-chrome'){await page.setViewportSize({width:1920,height:1080});const rail=await page.locator('.desktop-rail').boundingBox();const main=await page.locator('.app-main').boundingBox();expect(rail&&main?main.x-(rail.x+rail.width):Infinity).toBeLessThanOrEqual(48)}})

test('demo can execute a fast, contextual workout set',async({page})=>{await enterDemo(page);await page.getByRole('link',{name:/train/i}).first().click();await page.getByRole('button',{name:/start/i}).click();await expect(page.getByLabel(/live workout summary/i)).toBeVisible();await page.getByLabel(/set 1 weight/i).first().fill('20');await page.getByLabel(/set 1 reps/i).first().fill('6');await page.getByLabel(/set 1 note/i).first().fill('Controlled tempo');await page.getByRole('button',{name:/mark .* set 1 complete/i}).first().click();await expect(page.getByText(/1\/12 sets/i)).toBeVisible();await expect(page.getByText('120 kg volume')).toBeVisible();await expect(page.getByText(/rest 1:/i)).toBeVisible();await expect(page.getByRole('button',{name:/finish workout/i})).toBeEnabled()})

test('an unfinished workout draft survives a refresh',async({page})=>{await enterDemo(page);await page.getByRole('link',{name:/train/i}).first().click();await page.getByRole('button',{name:/start/i}).click();await page.getByLabel(/set 1 weight/i).first().fill('32.5');await page.getByLabel(/set 1 reps/i).first().fill('9');await page.getByLabel(/set 1 note/i).first().fill('Keep shoulder packed');await expect.poll(()=>page.evaluate(()=>Object.keys(localStorage).some((key)=>key.startsWith('dayframe_workout_draft_demo_')))).toBe(true);await page.reload();await page.getByRole('button',{name:/resume/i}).click();await expect(page.getByLabel(/set 1 weight/i).first()).toHaveValue('32.5');await expect(page.getByLabel(/set 1 reps/i).first()).toHaveValue('9');await expect(page.getByLabel(/set 1 note/i).first()).toHaveValue('Keep shoulder packed')})

test('demo Study session records a manual attempt and finishes',async({page})=>{await enterDemo(page);await page.getByRole('link',{name:/study/i}).first().click();await page.getByRole('button',{name:/start session/i}).click();await page.getByRole('button',{name:/log result/i}).first().click();await page.getByRole('dialog',{name:/log study result/i}).locator('select').first().selectOption('independent');await page.getByRole('button',{name:/save result/i}).click();await page.getByLabel('Closing note').fill('Traversal choice is clearer.');await page.getByRole('button',{name:/finish and save/i}).click();await expect(page.getByText(/current roadmap/i)).toBeVisible()})

test('nutrition summary is reviewed and does not hide itemized mode',async({page})=>{await enterDemo(page);await page.goto('/#/nutrition');await expect(page.getByRole('heading',{name:/fuel, without the fuss/i})).toBeVisible();await page.getByRole('button',{name:/enter daily summary/i}).click();await page.getByLabel('Calories').fill('2100');await page.getByLabel('Protein (g)').fill('140');await page.getByLabel('Carbs (g)').fill('220');await page.getByLabel('Fat (g)').fill('70');await page.getByLabel('Fiber (g)').fill('30');await page.getByRole('button',{name:/save authoritative summary/i}).click();await expect(page.getByText(/daily summary is the total/i)).toBeVisible()})

test('Quick Add opens contextual categories before actions',async({page})=>{await enterDemo(page);await page.getByRole('button',{name:/quick add/i}).click();const dialog=page.getByRole('dialog');for(const name of ['Train','Study','Health','Life'])await expect(dialog.getByRole('button',{name,exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Health',exact:true}).click();await expect(dialog.getByRole('button',{name:/water/i})).toBeVisible()})

test('Progress range filters show honest evidence',async({page})=>{await enterDemo(page);await page.getByRole('link',{name:/progress/i}).first().click();await page.getByRole('button',{name:'7D'}).click();await page.getByRole('button',{name:'Study'}).click();await expect(page.getByText(/independent solve rate/i)).toBeVisible()})

test('legacy routes redirect to V2 destinations',async({page})=>{await enterDemo(page);await page.goto('/#/food');await expect(page.getByRole('heading',{name:/fuel, without the fuss/i})).toBeVisible();await page.goto('/#/insights');await expect(page.getByRole('heading',{name:/evidence over guesses/i})).toBeVisible()})

test('demo profile offers a route to real sign in',async({page})=>{await enterDemo(page);await page.goto('/#/settings');await expect(page.getByRole('button',{name:/create account or sign in/i})).toBeVisible()})

test('first-use training starts with education, preferences and day-ranked templates',async({page})=>{await enterDemo(page);await page.evaluate(()=>localStorage.setItem('dayframe_v2_demo_data',JSON.stringify({plans:[],sessions:[],studySessions:[],attempts:[],notes:[],reviews:[],summaries:[]})));await page.goto('/#/train');const tabs=page.getByRole('button').filter({hasText:/^(Templates|Today|Program|History)$/});await expect(tabs.first()).toHaveText('Templates');await expect(page.getByText(/How training templates work/i)).toBeVisible();await expect(page.getByLabel('Main goal')).toBeVisible();await page.getByLabel('Days available each week').fill('5');await page.getByRole('button',{name:/update recommendations/i}).click();const best=page.locator('.recommended-card').first();await expect(best).toContainText('5 days');await expect(best).toContainText('Best match')})

test('resetting a study roadmap preserves history language and reopens Templates',async({page})=>{await enterDemo(page);await page.getByRole('link',{name:/study/i}).first().click();await page.getByRole('tab',{name:'Roadmap'}).click();await page.getByRole('button',{name:/choose a different template/i}).click();await expect(page.getByText(/completed sessions, attempts and notes are preserved/i)).toBeVisible();await page.getByRole('button',{name:/archive and choose again/i}).click();await expect(page.getByRole('tab',{name:'Templates'})).toHaveAttribute('aria-selected','true');await expect(page.getByText(/How study templates work/i)).toBeVisible();await expect(page.getByLabel(/what are you studying/i)).toBeVisible()})

test('interview roadmap copies exact dates, carries baseline work and records a scored problem',async({page})=>{await enterDemo(page);await page.evaluate(()=>localStorage.setItem('dayframe_v2_demo_data',JSON.stringify({plans:[],sessions:[],studySessions:[],attempts:[],notes:[],reviews:[],problemAttempts:[],summaries:[]})));await page.goto('/#/study');await page.reload();await page.getByLabel('Outcome to compare').selectOption('Prepare for interviews');const template=page.locator('article').filter({has:page.getByRole('heading',{name:'Software Engineering Interview Preparation'})});await template.getByRole('button',{name:/preview roadmap/i}).click();await expect(template.getByLabel('Start date')).toHaveValue('2026-09-01');await template.getByRole('button',{name:/copy template/i}).click();await expect(page.getByText('3Sum Closest',{exact:true}).first()).toBeVisible();await page.getByRole('button',{name:/use my aug 31 baseline/i}).click();await expect(page.getByText('Container With Most Water',{exact:true}).first()).toBeVisible();await page.getByText('3Sum Closest',{exact:true}).first().click();const detail=page.getByRole('dialog',{name:'3Sum Closest'});await expect(detail.getByRole('link',{name:/open leetcode/i})).toHaveAttribute('href','https://leetcode.com/problems/3sum-closest/');await detail.locator('.score-button').nth(1).click();await detail.getByRole('button',{name:/save score and complete/i}).click();await page.getByRole('tab',{name:'Roadmap'}).click();await page.getByPlaceholder(/Search 3Sum/).fill('Trapping Rain Water');await expect(page.getByText('Trapping Rain Water',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false)})
