import { useState, type FormEvent } from 'react'
import { Calculator, Camera, Check, CookingPot, FileImage, Plus, Search, ShieldCheck, Utensils } from 'lucide-react'
import { Sheet } from '../components/Sheet'
import { useData } from '../context/DataContext'
import { useNutritionPreferences, useNutritionSummary, useRecipes, useV2Mutation } from '../hooks/useV2'
import { dateKey, nutritionTotal } from '../lib/v2'
import { saveNutritionSummary, saveRecipe, setNutritionMode } from '../repositories/v2Repository'
import type { NutritionValues } from '../types/v2'

type Tab='daily'|'meals'|'advanced'
export function FoodPage(){const data=useData();const date=dateKey(data.selectedDate);const[tab,setTab]=useState<Tab>('daily');const[summaryOpen,setSummaryOpen]=useState(false);const[importOpen,setImportOpen]=useState(false);const[recipeOpen,setRecipeOpen]=useState(false);const summary=useNutritionSummary(date);const preferences=useNutritionPreferences();const total=nutritionTotal(summary.data,data.meals.map((meal)=>({...meal,fiber:0})));const targets={calories:Number(preferences.data?.calorie_target??0),protein:Number(preferences.data?.protein_target_g??0),carbs:Number(preferences.data?.carbs_target_g??0),fat:Number(preferences.data?.fat_target_g??0),fiber:Number(preferences.data?.fiber_target_g??0)}
  return <div className="page"><header className="page-header"><div><p className="eyebrow">Nutrition · secondary</p><h1>Fuel, without the fuss.</h1><p className="muted">Use an authoritative daily summary or itemized meals—never both at once.</p></div></header><div className="tabs">{(['daily','meals','advanced']as Tab[]).map((item)=><button className={`tab ${tab===item?'active':''}`} key={item} onClick={()=>setTab(item)}>{item==='daily'?'Daily summary':item[0].toUpperCase()+item.slice(1)}</button>)}</div>
    {tab==='daily'&&<><section className="card food-total section"><div className="row-between"><div><span className="muted small">Calories · {total.source==='summary'?'authoritative summary':'itemized meals'}</span><div className="calorie-number">{Math.round(total.calories).toLocaleString()}</div><span className="muted small">{targets.calories?`of ${targets.calories.toLocaleString()} kcal from your preferences`:'Set a calorie target in Settings'}</span></div><span className="icon-bubble"><Utensils/></span></div><div className="macro-row"><Macro value={total.protein} target={targets.protein} label="Protein"/><Macro value={total.carbs} target={targets.carbs} label="Carbs"/><Macro value={total.fat} target={targets.fat} label="Fat"/><Macro value={total.fiber} target={targets.fiber} label="Fiber"/></div></section><div className="grid-2 section"><button className="card card-pad action-card" onClick={()=>setSummaryOpen(true)}><Calculator/><strong>{summary.data?'Edit daily summary':'Enter daily summary'}</strong><span>Calories and macros from another trusted log</span></button><button className="card card-pad action-card" onClick={()=>setImportOpen(true)}><Camera/><strong>Import screenshot</strong><span>Extract → review → correct → confirm</span></button></div>{summary.data&&<SummaryMode summary={summary.data}/>}<p className="insight-callout section small">{total.source==='summary'?'The daily summary is the total. Meal entries remain visible for reference but are not added.':'Meal entries are being summed. Any saved summary remains available but is excluded.'}</p></>}
    {tab==='meals'&&<Meals/>}{tab==='advanced'&&<Advanced onRecipe={()=>setRecipeOpen(true)}/>}<SummarySheet open={summaryOpen} onClose={()=>setSummaryOpen(false)} date={date}/><ImportSheet open={importOpen} onClose={()=>setImportOpen(false)} date={date}/><RecipeSheet open={recipeOpen} onClose={()=>setRecipeOpen(false)}/></div>}

function Meals(){const data=useData();const[open,setOpen]=useState(false);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);data.addMeal({name:String(f.get('name')),meal:String(f.get('meal')) as 'Breakfast'|'Lunch'|'Dinner'|'Snack',calories:Number(f.get('calories')),protein:Number(f.get('protein')),carbs:Number(f.get('carbs')),fat:Number(f.get('fat')),source:'user_entered'});setOpen(false)};return <section className="section"><div className="section-title"><h2>Individual meals</h2><button className="btn btn-primary btn-small" onClick={()=>setOpen(true)}><Plus size={15}/>Add meal</button></div><div className="card card-pad">{data.meals.length?data.meals.map((item)=><div className="meal-row" key={item.id}><div><strong>{item.name}</strong><div className="tiny muted">{item.meal} · {item.protein}g protein · {item.source.replace('_',' ')}</div></div><strong>{item.calories} kcal</strong></div>):<div className="empty-state">No meals on this day.</div>}</div><Sheet open={open} onClose={()=>setOpen(false)} title="Add individual meal" description="Optional macros can be zero when unknown."><form className="form-grid" onSubmit={submit}><label className="field"><span>Name</span><input className="input" name="name" required/></label><label className="field"><span>Meal</span><select className="select" name="meal"><option>Breakfast</option><option>Lunch</option><option>Dinner</option><option>Snack</option></select></label><MacroInputs/><button className="btn btn-primary">Save meal</button></form></Sheet></section>}

function SummaryMode({summary}:{summary:NonNullable<ReturnType<typeof useNutritionSummary>['data']>}){const mode=useV2Mutation((identity,value:boolean)=>setNutritionMode(identity,summary.id,value));return <section className="card card-pad section row-between"><div><strong>{summary.use_as_daily_total?'Daily summary is authoritative':'Itemized mode is authoritative'}</strong><p className="muted small" style={{margin:'4px 0 0'}}>Switching does not delete either source.</p></div><button className="btn btn-secondary btn-small" onClick={()=>mode.mutate(!summary.use_as_daily_total)}>{summary.use_as_daily_total?'Use meals':'Use summary'}</button></section>}

function SummarySheet({open,onClose,date}:{open:boolean;onClose:()=>void;date:string}){const save=useV2Mutation((identity,values:NutritionValues)=>saveNutritionSummary(identity,date,values,'manual'));const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);save.mutate(readMacros(f),{onSuccess:onClose})};return <Sheet open={open} onClose={onClose} title="Daily nutrition summary" description="This becomes the daily total and will not be added to meals."><form className="form-grid" onSubmit={submit}><MacroInputs fiber/><button className="btn btn-primary" disabled={save.isPending}>Save authoritative summary</button>{save.error&&<p className="field-error">{save.error.message}</p>}</form></Sheet>}

function ImportSheet({open,onClose,date}:{open:boolean;onClose:()=>void;date:string}){const[step,setStep]=useState<'select'|'review'>('select');const[file,setFile]=useState('');const save=useV2Mutation((identity,values:NutritionValues)=>saveNutritionSummary(identity,date,values,'screenshot'));const close=()=>{setStep('select');setFile('');onClose()};const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();save.mutate(readMacros(new FormData(e.currentTarget)),{onSuccess:close})};return <Sheet open={open} onClose={close} title="Import nutrition screenshot" description={step==='select'?'Select an image. Nothing is retained by default.':'Review and correct every value before saving.'}>{step==='select'?<div className="form-grid"><label className="card card-pad action-card"><FileImage/><strong>Select screenshot</strong><span>PNG, JPEG or WebP</span><input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={(e)=>{const picked=e.target.files?.[0];if(picked){setFile(picked.name);setStep('review')}}}/></label><div className="insight-callout small"><ShieldCheck size={16} style={{verticalAlign:-3,marginRight:6}}/><strong>Automatic extraction unavailable.</strong><p className="muted" style={{margin:'6px 0 0'}}>No server-side vision provider is configured. Dayframe will not pretend extraction succeeded. You can still enter the visible values manually in the required review step.</p></div></div>:<form className="form-grid" onSubmit={submit}><div className="row"><Check size={17}/><span className="small">{file} selected · image not uploaded or retained</span></div><MacroInputs fiber/><button className="btn btn-primary" disabled={save.isPending}>Confirm reviewed values</button>{save.error&&<p className="field-error">{save.error.message}</p>}</form>}</Sheet>}

function Advanced({onRecipe}:{onRecipe:()=>void}){const recipes=useRecipes();return <section className="section"><div className="section-title"><h2>Foods & recipes</h2><button className="btn btn-primary btn-small" onClick={onRecipe}><Plus size={15}/>New recipe</button></div><div className="grid-2">{recipes.data?.map((recipe)=><article className="card card-pad" key={recipe.id}><CookingPot/><h3 style={{marginTop:12}}>{recipe.name}</h3><p className="muted small">{recipe.servings} servings · persisted recipe</p></article>)}<article className="card card-pad"><Search/><h3 style={{marginTop:12}}>Custom foods</h3><p className="muted small">Foods created as recipe ingredients remain private and reusable.</p></article></div></section>}
function RecipeSheet({open,onClose}:{open:boolean;onClose:()=>void}){const save=useV2Mutation((identity,input:{name:string;servings:number;ingredients:Array<{name:string;calories:number;protein:number}>})=>saveRecipe(identity,input));const[ingredients,setIngredients]=useState([{id:'1',name:'',calories:0,protein:0}]);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);save.mutate({name:String(f.get('name')),servings:Number(f.get('servings')),ingredients:ingredients.filter((i)=>i.name)},{onSuccess:onClose})};return <Sheet open={open} onClose={onClose} title="Build a reusable recipe" description="Ingredients and recipe rows are persisted to your account."><form className="form-grid" onSubmit={submit}><label className="field"><span>Name</span><input className="input" name="name" required/></label><label className="field"><span>Servings</span><input className="input" name="servings" type="number" min="1" defaultValue="4" required/></label>{ingredients.map((item,index)=><div className="card card-quiet card-pad" key={item.id}><label className="field"><span>Ingredient {index+1}</span><input className="input" value={item.name} onChange={(e)=>setIngredients((rows)=>rows.map((row)=>row.id===item.id?{...row,name:e.target.value}:row))} required/></label><div className="grid-2"><label className="field"><span>Calories</span><input className="input" type="number" min="0" value={item.calories} onChange={(e)=>setIngredients((rows)=>rows.map((row)=>row.id===item.id?{...row,calories:Number(e.target.value)}:row))}/></label><label className="field"><span>Protein (g)</span><input className="input" type="number" min="0" value={item.protein} onChange={(e)=>setIngredients((rows)=>rows.map((row)=>row.id===item.id?{...row,protein:Number(e.target.value)}:row))}/></label></div></div>)}<button className="btn btn-secondary" type="button" onClick={()=>setIngredients((rows)=>[...rows,{id:crypto.randomUUID(),name:'',calories:0,protein:0}])}><Plus size={15}/>Add ingredient</button><button className="btn btn-primary" disabled={save.isPending}>Save recipe</button>{save.error&&<p className="field-error">{save.error.message}</p>}</form></Sheet>}

function MacroInputs({fiber=false}:{fiber?:boolean}){return <div className="grid-2"><label className="field"><span>Calories</span><input className="input" name="calories" type="number" min="0" required/></label><label className="field"><span>Protein (g)</span><input className="input" name="protein" type="number" min="0" step="0.1" required/></label><label className="field"><span>Carbs (g)</span><input className="input" name="carbs" type="number" min="0" step="0.1" required/></label><label className="field"><span>Fat (g)</span><input className="input" name="fat" type="number" min="0" step="0.1" required/></label>{fiber&&<label className="field"><span>Fiber (g)</span><input className="input" name="fiber" type="number" min="0" step="0.1" required/></label>}</div>}
function readMacros(f:FormData):NutritionValues{return{calories:Number(f.get('calories')),protein:Number(f.get('protein')),carbs:Number(f.get('carbs')),fat:Number(f.get('fat')),fiber:Number(f.get('fiber')??0)}}
function Macro({value,target,label}:{value:number;target:number;label:string}){return <div className="macro"><strong>{Math.round(value)}g</strong><span>{label}{target?` · ${target}g`:''}</span><div className="macro-bar"><i style={{width:`${target?Math.min(100,value/target*100):0}%`}}/></div></div>}
