import { useState, type FormEvent } from 'react'
import { BookOpenText, FolderKanban, Heart, Map, Plus, Target } from 'lucide-react'
import { ProgressRing } from '../components/ProgressRing'
import { Sheet } from '../components/Sheet'
import { useData } from '../context/DataContext'
import { useIdentity, useLifeExtended, useV2Mutation } from '../hooks/useV2'
import { addLifeRecord } from '../repositories/v2Repository'

type Tab='focus'|'travel'|'notes'|'someday'
export function LifePage(){const[tab,setTab]=useState<Tab>('focus');const[open,setOpen]=useState(false);const data=useData();const extended=useLifeExtended();const identity=useIdentity();const add=useV2Mutation((_identity:typeof identity,input:{kind:'project'|'wish'|'note';title:string;detail?:string})=>addLifeRecord(_identity,input));const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const title=String(f.get('title'));const detail=String(f.get('detail')??'');if(tab==='focus'&&f.get('kind')==='goal')data.addGoal(title,'Personal');else if(tab==='travel')data.addTrip(title,String(f.get('country')));else add.mutate({kind:tab==='focus'?'project':tab==='notes'?'note':'wish',title,detail},{onSuccess:()=>setOpen(false)})}
  void identity
  return <div className="page"><header className="page-header"><div><p className="eyebrow">Life</p><h1>Keep the rest intentional.</h1><p className="muted">Focus, travel, notes, and ideas for someday—outside the daily center.</p></div><button className="btn btn-primary btn-icon" aria-label={`Add to ${tab}`} onClick={()=>setOpen(true)}><Plus/></button></header><div className="tabs">{(['focus','travel','notes','someday']as Tab[]).map((item)=><button className={`tab ${tab===item?'active':''}`} key={item} onClick={()=>setTab(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div>
    {tab==='focus'&&<section className="section"><div className="section-title"><h2>Goals & active projects</h2><span className="badge">next actions</span></div><div className="grid-2">{data.goals.filter((item)=>item.status==='active').map((goal)=><article className="card goal-card" key={goal.id}><span className="badge badge-neutral">Goal · {goal.category}</span><h2 style={{marginTop:14}}>{goal.title}</h2><div className="goal-progress"><ProgressRing value={goal.progress}/><div><span className="tiny muted">Next action</span><p className="small">{goal.nextAction}</p></div></div></article>)}{extended.data?.projects.map((project)=><article className="card card-pad" key={project.id}><span className="icon-bubble"><FolderKanban/></span><h2 style={{marginTop:14}}>{project.title}</h2><p className="muted small">Next: {project.next_action??'Define the next action'}</p><div className="progress-track"><div className="progress-fill" style={{width:`${Number(project.progress??0)}%`}}/></div></article>)}</div>{!data.goals.length&&!extended.data?.projects.length&&<Empty icon={<Target/>} text="No focus items yet."/>}</section>}
    {tab==='travel'&&<section className="section"><div className="grid-2">{data.trips.map((trip)=><article className="card card-pad" key={trip.id}><div className="trip-visual"><span className="tiny">{trip.country}</span><h2>{trip.destination}</h2></div><div className="row-between" style={{marginTop:12}}><span className="badge">{trip.status}</span><span className="muted small">{trip.dates}</span></div></article>)}</div>{!data.trips.length&&<Empty icon={<Map/>} text="No travel plans yet."/>}</section>}
    {tab==='notes'&&<section className="section"><div className="plan-list">{extended.data?.notes.map((note)=><article className="card card-pad" key={note.id}><span className="tiny muted">{note.note_date}</span><h3>{note.title??'Dated note'}</h3><p className="muted small preserve-lines">{note.content}</p></article>)}</div>{!extended.data?.notes.length&&<Empty icon={<BookOpenText/>} text="No general notes yet."/>}</section>}
    {tab==='someday'&&<section className="section"><div className="grid-2">{extended.data?.wishes.map((wish)=><article className="card card-pad" key={wish.id}><span className="icon-bubble"><Heart/></span><h2 style={{marginTop:14}}>{wish.title}</h2><span className="badge badge-neutral">{wish.status}</span>{wish.notes&&<p className="muted small section">{wish.notes}</p>}</article>)}</div>{!extended.data?.wishes.length&&<Empty icon={<Heart/>} text="Capture an idea without making it a task."/>}</section>}
    <Sheet open={open} onClose={()=>setOpen(false)} title={`Add to ${tab}`} description="This is saved privately to your account."><form className="form-grid" onSubmit={submit}>{tab==='focus'&&<label className="field"><span>Type</span><select className="select" name="kind"><option value="goal">Goal</option><option value="project">Project</option></select></label>}<label className="field"><span>{tab==='travel'?'Destination':'Title'}</span><input className="input" name="title" required/></label>{tab==='travel'&&<label className="field"><span>Country</span><input className="input" name="country" required/></label>}<label className="field"><span>{tab==='notes'?'Note':'Next action / details'}</span><textarea className="textarea" name="detail" required={tab==='notes'}/></label><button className="btn btn-primary" disabled={add.isPending}>Save</button>{add.error&&<p className="field-error">{add.error.message}</p>}</form></Sheet>
  </div>}
function Empty({icon,text}:{icon:React.ReactNode;text:string}){return <div className="card empty-state section">{icon}<p>{text}</p></div>}
