import { useMemo, useState } from 'react'
import { Activity, BookOpen, Brain, CheckCircle2, Dumbbell, Scale, TimerReset } from 'lucide-react'
import { useProgressData } from '../hooks/useV2'
import { independentSolveRate, noDataLabel, progressRange } from '../lib/v2'

type Range='7D'|'30D'|'3M'|'6M'|'1Y'|'Custom';type View='overview'|'train'|'study'|'body'
const defaultCustomRange=progressRange('30D')
export function ProgressPage(){const[range,setRange]=useState<Range>('30D');const[view,setView]=useState<View>('overview');const[customFrom,setCustomFrom]=useState(defaultCustomRange.from);const[customTo,setCustomTo]=useState(defaultCustomRange.to);const dates=useMemo(()=>range==='Custom'?{from:customFrom,to:customTo,label:'Custom'}:progressRange(range),[range,customFrom,customTo]);const query=useProgressData(dates.from,dates.to);const data=query.data
  const trainPlanned=data?.planned.filter((item)=>item.domain==='train')??[];const trainDone=trainPlanned.filter((item)=>item.status==='completed').length;const studyPlanned=data?.planned.filter((item)=>item.domain==='study')??[];const studyDone=studyPlanned.filter((item)=>item.status==='completed').length;const focused=(data?.studySessions??[]).filter((item)=>item.status==='completed').reduce((sum,item)=>sum+Number(item.actual_minutes??0),0);const rate=independentSolveRate(data?.attempts??[])
  return <div className="page"><header className="page-header"><div><p className="eyebrow">Progress</p><h1>Evidence over guesses.</h1><p className="muted">Every number below comes from records inside the selected range.</p></div></header><div className="range-picker" aria-label="Progress range">{(['7D','30D','3M','6M','1Y','Custom']as Range[]).map((item)=><button className={`tab ${range===item?'active':''}`} key={item} onClick={()=>setRange(item)}>{item}</button>)}</div>{range==='Custom'&&<div className="grid-2 section"><label className="field"><span>From</span><input className="input" type="date" value={customFrom} max={customTo} onChange={(e)=>setCustomFrom(e.target.value)}/></label><label className="field"><span>To</span><input className="input" type="date" value={customTo} min={customFrom} onChange={(e)=>setCustomTo(e.target.value)}/></label></div>}<div className="tabs section" role="tablist">{(['overview','train','study','body']as View[]).map((item)=><button className={`tab ${view===item?'active':''}`} key={item} onClick={()=>setView(item)}>{item==='body'?'Body / Health':item[0].toUpperCase()+item.slice(1)}</button>)}</div>
    {query.error&&<div className="auth-message section">Apply the V2 migrations to load Progress data. {query.error.message}</div>}{query.isLoading&&<div className="skeleton section"/>}
    {data&&<>{view==='overview'&&<div className="grid-3 section"><Metric icon={<Dumbbell/>} value={trainPlanned.length?`${trainDone}/${trainPlanned.length}`:'—'} label="planned workouts completed" empty={!trainPlanned.length}/><Metric icon={<BookOpen/>} value={studyPlanned.length?`${studyDone}/${studyPlanned.length}`:'—'} label="planned study sessions completed" empty={!studyPlanned.length}/><Metric icon={<TimerReset/>} value={focused?`${focused} min`:'—'} label="focused study time" empty={!focused}/></div>}
    {view==='train'&&<section className="section"><div className="grid-3"><Metric icon={<CheckCircle2/>} value={trainPlanned.length?`${Math.round(trainDone/trainPlanned.length*100)}%`:'—'} label="schedule adherence" empty={!trainPlanned.length}/><Metric icon={<Dumbbell/>} value={String(data.workouts.filter((item)=>item.status==='completed').length||'—')} label="persisted workouts" empty={!data.workouts.length}/><Metric icon={<Activity/>} value={String(data.sets.filter((item)=>item.completed).length||'—')} label="completed sets" empty={!data.sets.length}/></div><Evidence text={noDataLabel(data.workouts.length)??'Workout history is calculated from completed workout sessions and set logs in this range.'}/></section>}
    {view==='study'&&<section className="section"><div className="grid-3"><Metric icon={<BookOpen/>} value={studyPlanned.length?`${studyDone}/${studyPlanned.length}`:'—'} label="planned sessions" empty={!studyPlanned.length}/><Metric icon={<TimerReset/>} value={focused?`${focused} min`:'—'} label="focused minutes" empty={!focused}/><Metric icon={<Brain/>} value={rate===null?'—':`${rate}%`} label="independent solve rate" empty={rate===null}/></div><Evidence text={rate===null?'Not enough problem attempts yet. Solve-rate appears only after manual outcomes are recorded.':`${data.attempts.filter((item)=>item.result==='independent').length} independent results among ${data.attempts.filter((item)=>['independent','hint','solution_assisted','partial','failed'].includes(item.result)).length} problem attempts.`}/></section>}
    {view==='body'&&<section className="section"><div className="grid-3"><Metric icon={<Scale/>} value={data.body.length?`${Number(data.body.at(-1)?.weight_kg??0).toFixed(1)} kg`:'—'} label="latest bodyweight" empty={!data.body.length}/><Metric icon={<Activity/>} value={String(data.activity.reduce((sum,item)=>sum+Number(item.steps??0),0)||'—')} label="steps logged" empty={!data.activity.length}/><Metric icon={<Activity/>} value={String(data.body.length||'—')} label="measurement records" empty={!data.body.length}/></div><Evidence text={noDataLabel(data.body.length+data.activity.length)??'Body and activity context uses only logged measurements; no medical or causal inference is generated.'}/></section>}</>}
  </div>}
function Metric({icon,value,label,empty}:{icon:React.ReactNode;value:string;label:string;empty:boolean}){return <article className="card card-pad"><span className="icon-bubble">{icon}</span><span className="metric-value" style={{marginTop:14}}>{value}</span><span className="metric-label">{label}</span>{empty&&<span className="tiny muted">Not enough data yet</span>}</article>}
function Evidence({text}:{text:string}){return <div className="insight-callout section small">{text}</div>}
