import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { addDays, format, startOfWeek } from 'date-fns'
import { BookOpen, Check, ChevronRight, Clock3, ExternalLink, FileUp, Library, NotebookPen, Play, RotateCcw, Search, TimerReset, Trash2 } from 'lucide-react'
import { TemplateGuide } from '../components/TemplateGuide'
import { useData } from '../context/DataContext'
import { useCopyTemplate, useIdentity, usePlans, usePlannedSessions, useResources, useStudyNotes, useTemplates, useV2Mutation } from '../hooks/useV2'
import { addStudyAttempt, addStudyNote, deleteStudyNote, finishStudySession, resetDomainPlans, scheduleStudyReview, startStudySession, updatePlan, updatePlannedSession } from '../repositories/v2Repository'
import { dateKey, mapAttemptLabel, reviewDate } from '../lib/v2'
import type { PlannedItem, PlannedSession, PlanTemplate, StudyAttempt, StudyNote, StudyResult, StudySession } from '../types/v2'
import { usePersonalization } from '../hooks/usePersonalization'

type View = 'templates' | 'today' | 'roadmap' | 'notebook' | 'resources'

export function StudyPage() {
  const [view,setView]=useState<View>('templates')
  const [active,setActive]=useState<StudySession|null>(null)
  const [activePlanSession,setActivePlanSession]=useState<PlannedSession|null>(null)
  const {selectedDate}=useData(); const today=dateKey(selectedDate)
  const weekStart=dateKey(startOfWeek(selectedDate,{weekStartsOn:1})); const weekEnd=dateKey(addDays(new Date(`${weekStart}T12:00:00`),6))
  const plans=usePlans('study'); const sessions=usePlannedSessions(weekStart,weekEnd,'study')
  const roadmapSessions=usePlannedSessions(dateKey(addDays(selectedDate,-365)),dateKey(addDays(selectedDate,365)),'study')
  const activePlan=plans.data?.find((item)=>item.status==='active')??plans.data?.find((item)=>item.status==='paused')
  const weekSessions=(sessions.data??[]).filter((item)=>item.plan_id===activePlan?.id)
  const current=weekSessions.find((item)=>item.scheduled_date===today&&item.status!=='completed') ?? weekSessions.find((item)=>item.status==='active') ?? weekSessions.find((item)=>item.status==='planned')
  const currentView=activePlan&&view==='templates'?'today':view
  const tabs:View[]=activePlan?['today','roadmap','notebook','resources']:['templates','today','roadmap','notebook','resources']

  return <div className="page">
    <header className="page-header"><div><p className="eyebrow">Study</p><h1>Build knowledge that holds.</h1><p className="muted">Follow a roadmap, practise deliberately, and keep the evidence.</p></div></header>
    {!active && <div className="tabs" role="tablist" aria-label="Study views">{tabs.map((item)=><button className={`tab ${currentView===item?'active':''}`} role="tab" aria-selected={currentView===item} key={item} onClick={()=>setView(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div>}
    {active && activePlanSession ? <ActiveStudy session={active} planned={activePlanSession} onFinish={()=>{setActive(null);setActivePlanSession(null)}}/> : <>
      {currentView==='templates'&&!activePlan&&<StudyTemplates/>}
      {currentView==='today'&&<StudyToday activePlan={activePlan} current={current} sessions={weekSessions} onStarted={(study,planned)=>{setActive(study);setActivePlanSession(planned)}}/>}
      {currentView==='roadmap'&&<Roadmap plan={activePlan} sessions={(roadmapSessions.data??[]).filter((item)=>item.plan_id===activePlan?.id)} onReset={()=>setView('templates')}/>}
      {currentView==='notebook'&&<Notebook planId={activePlan?.id}/>}
      {currentView==='resources'&&<Resources/>}
    </>}
  </div>
}

interface StudySetupValues { subject:string;goal:string;level:string;weekly_hours:number;target_date:string }
function StudySetup({onSaved}:{onSaved:(values:StudySetupValues)=>void}){const personalization=usePersonalization();const setup=personalization.getDomainSetup('study');const[saving,setSaving]=useState(false);const[error,setError]=useState('');const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);setError('');const form=new FormData(event.currentTarget);const values={subject:String(form.get('subject')),goal:String(form.get('goal')),level:String(form.get('level')),weekly_hours:Number(form.get('hours')),target_date:String(form.get('target_date')??'')};try{await personalization.saveDomainSetup('study',values);onSaved(values)}catch(value){setError(value instanceof Error?value.message:'Study preferences could not be saved.')}finally{setSaving(false)}};return <section className="card card-pad section progressive-setup"><p className="eyebrow">{setup?'Your study preferences':'First, personalize the catalog'}</p><h2>What are you building toward?</h2><p className="muted small">These answers rank roadmaps and set a realistic pace. They do not choose or activate anything for you.</p><form className="form-grid section" onSubmit={submit}><label className="field"><span>What are you studying?</span><input className="input" name="subject" defaultValue={String(setup?.subject??'')} placeholder="e.g. computer science, an exam, a language" required/></label><div className="grid-2"><label className="field"><span>Desired outcome</span><select className="select" name="goal" defaultValue={String(setup?.goal??'Build foundations')}><option>Build foundations</option><option>Prepare for interviews</option><option>Deepen technical skills</option><option>Prepare for an exam</option><option>Complete a personal project</option></select></label><label className="field"><span>Current level</span><select className="select" name="level" defaultValue={String(setup?.level??'Starting fresh')}><option>Starting fresh</option><option>Know the basics</option><option>Intermediate</option><option>Advanced</option></select></label><label className="field"><span>Hours available each week</span><input className="input" name="hours" type="number" min="1" max="60" defaultValue={Number(setup?.weekly_hours)||6} required/></label><label className="field"><span>Target date (optional)</span><input className="input" name="target_date" type="date" defaultValue={String(setup?.target_date??'')}/></label></div>{error&&<p className="field-error">{error}</p>}<div className="row progressive-actions"><button className="btn btn-primary" disabled={saving}>{saving?'Saving…':setup?'Update recommendations':'Save and rank roadmaps'}</button>{!setup&&<button className="btn btn-ghost" type="button" onClick={()=>void personalization.skipDomainSetup('study')}>Skip for now</button>}</div></form></section>}

function StudyToday({activePlan,current,sessions,onStarted}:{activePlan?:{id:string;name:string;expected_minutes_per_week?:number|null};current?:PlannedSession;sessions:PlannedSession[];onStarted:(session:StudySession,planned:PlannedSession)=>void}){
  const identity=useIdentity(); const start=useV2Mutation((_identity:typeof identity,planned:PlannedSession)=>startStudySession(_identity,planned))
  void identity
  if(!activePlan)return <section className="card card-pad section empty-state"><BookOpen size={28}/><h2>No active study roadmap</h2><p>Open Templates to answer a few study questions, preview a researched roadmap, and copy your own schedule.</p></section>
  const completed=sessions.filter((item)=>item.status==='completed').length
  return <>
    <section className="card today-hero section"><div className="row-between"><span className="badge" style={{background:'rgba(245,240,231,.13)',color:'#F5F0E7'}}>Current roadmap</span><span className="small muted">{completed}/{sessions.length} this week</span></div>
      <div className="hero-workout"><div><p className="muted small">{current?.status==='active'?'In progress':current?'Scheduled':'No session due today'}</p><h2>{current?.title??activePlan.name}</h2><p className="muted small">{current?`${current.estimated_minutes??60} min · ${(current.planned_items??[]).length} tasks`:'Open Roadmap to see the next block.'}</p></div>{current&&<button className="btn btn-primary" disabled={start.isPending} onClick={()=>start.mutate(current,{onSuccess:(value)=>onStarted(value as StudySession,current)})}><Play size={17}/>{current.status==='active'?'Resume':'Start session'}</button>}</div>
      {start.error&&<p className="field-error">{start.error.message}</p>}
    </section>
    <section className="section"><div className="section-title"><h2>This week</h2><span className="badge">{completed} complete</span></div><div className="card card-pad plan-list">{sessions.length?sessions.map((session)=><div className="schedule-row" key={session.id}><span className={`status-dot ${session.status}`}/><div><strong>{session.title}</strong><div className="tiny muted">{format(new Date(`${session.scheduled_date}T12:00:00`),'EEE, MMM d')} · {session.estimated_minutes??60} min</div></div><span className="badge badge-neutral">{session.status.replace('_',' ')}</span></div>):<div className="empty-state">No sessions scheduled this week.</div>}</div></section>
  </>
}

function StudyTemplates(){
  const templates=useTemplates('study');const copy=useCopyTemplate();const personalization=usePersonalization();const setup=personalization.getDomainSetup('study');const [goal,setGoal]=useState(String(setup?.goal??'Build foundations'));const [hours,setHours]=useState(Number(setup?.weekly_hours)||6);const [preview,setPreview]=useState<PlanTemplate|null>(null);const [startDate,setStartDate]=useState(dateKey())
  const identity=useIdentity()
  useEffect(()=>{if(copy.data)void updatePlan({user:identity.user,isDemo:identity.isDemo},copy.data,{goal,expected_minutes_per_week:hours*60})},[copy.data,goal,hours,identity.isDemo,identity.user])
  const fitScore=(template:PlanTemplate)=>{const goalMatch=goal.toLowerCase().includes('interview')?template.slug.includes('interview'):template.slug.includes('cs');const expected=template.version.expected_hours_per_week??hours;return (goalMatch?0:100)+Math.abs(expected-hours)}
  const recommended=[...(templates.data?.filter((item)=>item.version.content.content_status==='complete')??[])].sort((a,b)=>fitScore(a)-fitScore(b))
  const togglePreview=(template:PlanTemplate)=>{copy.reset();setPreview((current)=>current?.id===template.id?null:template)}
  return <section className="section"><TemplateGuide domain="study"/><StudySetup onSaved={(values)=>{setGoal(values.goal);setHours(values.weekly_hours)}}/><div className="card card-pad section"><p className="eyebrow">Ranked recommendations</p><h2>Choose a roadmap that fits.</h2><div className="grid-2"><label className="field"><span>Outcome to compare</span><select className="select" value={goal} onChange={(event)=>setGoal(event.target.value)}><option>Build foundations</option><option>Prepare for interviews</option><option>Deepen technical skills</option><option>Prepare for an exam</option><option>Complete a personal project</option></select></label><label className="field"><span>Weekly hours to compare</span><input className="input" type="number" min="1" max="60" value={hours} onChange={(event)=>setHours(Number(event.target.value))}/></label></div><p className="muted small" style={{marginTop:12}}>The closest complete roadmap appears first. Preview its phases and workload before creating your private copy.</p></div>
    <div className="grid-2 section">{recommended.map((template,index)=>{const expanded=preview?.id===template.id;return <article className={`card card-pad ${index===0?'recommended-card':''}`} key={template.id}><div className="row-between"><span className="badge">{template.version.duration_weeks} weeks</span>{index===0?<span className="badge">Best match</span>:<span className="tiny muted">{template.version.expected_hours_per_week} h/week</span>}</div><h2 style={{marginTop:14}}>{template.name}</h2><p className="muted small">{template.short_description}</p><button className="btn btn-secondary" aria-expanded={expanded} onClick={()=>togglePreview(template)}>{expanded?'Hide details':<>Preview roadmap <ChevronRight size={16}/></>}</button>
      {expanded&&<div className="template-inline-preview"><div className="row-between"><p className="eyebrow">Curated by Dayframe · v{template.version.version}</p><button className="btn btn-ghost btn-small" onClick={()=>setPreview(null)}>Close</button></div><div className="metric-grid"><div><strong>{template.version.duration_weeks}</strong><span>weeks</span></div><div><strong>{template.version.content.phases.length}</strong><span>phases</span></div><div><strong>{hours}</strong><span>your hours/week</span></div></div><label className="field section"><span>Start date</span><input className="input" type="date" value={startDate} onChange={(event)=>setStartDate(event.target.value)}/></label><button className="btn btn-primary" disabled={copy.isPending} onClick={()=>copy.mutate({template,startDate})}>{copy.isPending?'Copying complete roadmap…':'Copy template'}</button>{copy.isSuccess&&<p className="auth-message">Roadmap copied. Today and Roadmap now use your persisted schedule.</p>}{copy.error&&<p className="field-error">{copy.error.message}</p>}<p className="tiny muted" style={{marginTop:14}}>Dayframe is not affiliated with or endorsed by referenced course or problem providers.</p></div>}
    </article>})}</div>
  </section>
}

function ActiveStudy({session,planned,onFinish}:{session:StudySession;planned:PlannedSession;onFinish:()=>void}){
  const identity=useIdentity();const [seconds,setSeconds]=useState(0);const [paused,setPaused]=useState(false);const [focus,setFocus]=useState(4);const [notes,setNotes]=useState('');const [logging,setLogging]=useState<PlannedItem|null>(null)
  void identity
  const finish=useV2Mutation((_identity:typeof identity,input:{session:StudySession;focus:number;notes:string})=>finishStudySession(_identity,input.session,input.focus,input.notes))
  useEffect(()=>{if(paused)return;const id=window.setInterval(()=>setSeconds((value)=>value+1),1000);return()=>window.clearInterval(id)},[paused])
  return <><div className="rest-timer"><div className="row"><Clock3 size={18}/><div><strong>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</strong><div className="tiny">{planned.title}</div></div></div><button className="btn btn-ghost btn-icon" style={{color:'inherit'}} onClick={()=>setPaused((value)=>!value)} aria-label={paused?'Resume timer':'Pause timer'}>{paused?<Play size={17}/>:<TimerReset size={17}/>}</button></div><p className="eyebrow">Active study session</p><h1>{planned.title}</h1><p className="muted">Planned {planned.estimated_minutes??60} minutes. Capture outcomes, not every minute.</p>
    <section className="section plan-list">{(planned.planned_items??[]).map((item,index)=><article className="card card-pad row-between" key={item.id}><div><span className="tiny muted">{index+1} · {item.item_type}</span><h3>{item.title}</h3></div><button className="btn btn-secondary btn-small" onClick={()=>setLogging(item)}>{item.status==='completed'?<><Check size={15}/> Logged</>:<>Log result</>}</button></article>)}</section>
    <section className="card card-pad section"><h2>Finish session</h2><div className="grid-2"><label className="field"><span>Focus (1–5)</span><input className="input" type="number" min="1" max="5" value={focus} onChange={(e)=>setFocus(Number(e.target.value))}/></label><label className="field"><span>Closing note</span><input className="input" value={notes} onChange={(e)=>setNotes(e.target.value)} placeholder="What changed in your understanding?"/></label></div><button className="btn btn-primary section" disabled={finish.isPending} onClick={()=>finish.mutate({session,focus,notes},{onSuccess})}>Finish and save</button>{finish.error&&<p className="field-error">{finish.error.message}</p>}</section>
    {logging&&<AttemptForm item={logging} session={session} onClose={()=>setLogging(null)}/>}</>
  function onSuccess(){onFinish()}
}

function AttemptForm({item,session,onClose}:{item:PlannedItem;session:StudySession;onClose:()=>void}){
  const identity=useIdentity();const log=useV2Mutation((_identity:typeof identity,input:{session:StudySession;item:PlannedItem;result:StudyResult;duration_seconds:number;confidence_after:number;what_i_missed:string})=>addStudyAttempt(_identity,input));const [result,setResult]=useState('independent');const [duration,setDuration]=useState(25);const [confidence,setConfidence]=useState(3);const [missed,setMissed]=useState('');const [review,setReview]=useState<'tomorrow'|'3d'|'7d'|'21d'|'skip'>('7d')
  const submit=(e:FormEvent)=>{e.preventDefault();log.mutate({session,item,result:mapAttemptLabel(result),duration_seconds:duration*60,confidence_after:confidence,what_i_missed:missed},{onSuccess:async(value)=>{if(review!=='skip')await scheduleStudyReview(identity,{task_id:(value as StudyAttempt).study_task_id,scheduled_for:reviewDate(review)});onClose()}})}
  return <div className="inline-dialog" role="dialog" aria-label="Log study result"><form className="card card-pad form-grid" onSubmit={submit}><div className="row-between"><div><p className="eyebrow">Task outcome</p><h2>{item.title}</h2></div><button className="btn btn-ghost" type="button" onClick={onClose}>Close</button></div><label className="field"><span>Result</span><select className="select" value={result} onChange={(e)=>setResult(e.target.value)}><option value="independent">Solved independently</option><option value="hint">Used hint</option><option value="solution_assisted">Solution assisted</option><option value="partial">Partial</option><option value="failed">Failed</option><option value="completed">Completed</option></select></label><div className="grid-2"><label className="field"><span>Duration (min)</span><input className="input" type="number" min="1" value={duration} onChange={(e)=>setDuration(Number(e.target.value))}/></label><label className="field"><span>Confidence (1–5)</span><input className="input" type="number" min="1" max="5" value={confidence} onChange={(e)=>setConfidence(Number(e.target.value))}/></label></div><label className="field"><span>What I missed</span><textarea className="textarea" value={missed} onChange={(e)=>setMissed(e.target.value)} placeholder="Optional gap, edge case, or correction"/></label><label className="field"><span>Schedule review</span><select className="select" value={review} onChange={(e)=>setReview(e.target.value as typeof review)}><option value="tomorrow">Tomorrow</option><option value="3d">3 days</option><option value="7d">7 days</option><option value="21d">21 days</option><option value="skip">Skip</option></select></label><button className="btn btn-primary" disabled={log.isPending}>Save result</button>{log.error&&<p className="field-error">{log.error.message}</p>}</form></div>
}

function Roadmap({plan,sessions,onReset}:{plan?:{id:string;name:string;start_date?:string|null;target_date?:string|null};sessions:PlannedSession[];onReset:()=>void}){
  const identity=useIdentity();const[confirmReset,setConfirmReset]=useState(false);const change=useV2Mutation((_identity:typeof identity,input:{id:string;status?:'skipped';scheduled_date?:string})=>updatePlannedSession(_identity,input.id,input.status?{status:input.status}:{status:'rescheduled',scheduled_date:input.scheduled_date}));const reset=useV2Mutation<void>((_identity)=>resetDomainPlans(_identity,'study'))
  void identity
  const complete=sessions.filter((item)=>item.status==='completed').length;const percent=sessions.length?Math.round(complete/sessions.length*100):0
  if(!plan)return <div className="empty-state card section"><BookOpen size={28}/><h2>Choose a roadmap first</h2><p>Open Templates to preview and copy a curated plan.</p></div>
  return <section className="section"><article className="card card-pad"><p className="eyebrow">Active roadmap</p><h2>{plan.name}</h2><div className="row-between"><span className="muted small">{complete} of {sessions.length} roadmap sessions</span><strong>{percent}%</strong></div><div className="progress-track"><div className="progress-fill" style={{width:`${percent}%`}}/></div><button className="btn btn-ghost btn-small section" onClick={()=>setConfirmReset(true)}><RotateCcw size={15}/>Choose a different template</button></article>{confirmReset&&<article className="card card-pad section reset-template-card"><p className="eyebrow">Reset active template?</p><h2>Your learning evidence stays safe.</h2><p className="muted small">Dayframe will archive this roadmap and its remaining schedule, then show Templates again. Completed sessions, attempts and notes are preserved.</p><div className="row progressive-actions"><button className="btn btn-primary" disabled={reset.isPending} onClick={()=>reset.mutate(undefined,{onSuccess:onReset})}>{reset.isPending?'Resetting…':'Archive and choose again'}</button><button className="btn btn-ghost" disabled={reset.isPending} onClick={()=>setConfirmReset(false)}>Keep current roadmap</button></div>{reset.error&&<p className="field-error">{reset.error.message}</p>}</article>}<div className="plan-list section">{sessions.map((item)=><article className="card card-pad" key={item.id}><div className="row-between"><div><span className="tiny muted">{format(new Date(`${item.scheduled_date}T12:00:00`),'EEEE, MMM d')}</span><h3>{item.title}</h3><span className="tiny muted">{item.estimated_minutes} min · {item.planned_items?.length??0} tasks</span></div><span className="badge badge-neutral">{item.status.replace('_',' ')}</span></div>{item.status==='planned'&&<div className="row" style={{marginTop:10}}><button className="btn btn-ghost btn-small" onClick={()=>change.mutate({id:item.id,status:'skipped'})}>Skip</button><button className="btn btn-secondary btn-small" onClick={()=>change.mutate({id:item.id,scheduled_date:dateKey(addDays(new Date(`${item.scheduled_date}T12:00:00`),1))})}>Move +1 day</button></div>}</article>)}</div><p className="muted small section">Missed work can be rescheduled or skipped without a punitive streak. The public template remains unchanged.</p></section>
}

function Notebook({planId}:{planId?:string}){
  const notes=useStudyNotes();const identity=useIdentity();const add=useV2Mutation((_identity:typeof identity,input:{plan_id?:string;note_type:StudyNote['note_type'];title:string;content:string})=>addStudyNote(_identity,input));const remove=useV2Mutation((_identity:typeof identity,id:string)=>deleteStudyNote(_identity,id));const [query,setQuery]=useState('');const [filter,setFilter]=useState<'all'|StudyNote['note_type']>('all')
  void identity
  const shown=useMemo(()=>(notes.data??[]).filter((item)=>(filter==='all'||item.note_type===filter)&&`${item.title} ${item.content}`.toLowerCase().includes(query.toLowerCase())),[notes.data,filter,query])
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);add.mutate({plan_id:planId,note_type:String(form.get('type')) as StudyNote['note_type'],title:String(form.get('title')),content:String(form.get('content'))},{onSuccess:()=>event.currentTarget.reset()})}
  return <section className="section"><form className="card card-pad form-grid" onSubmit={submit}><div><p className="eyebrow">Structured note</p><h2>Capture understanding, not just text.</h2></div><div className="grid-2"><label className="field"><span>Type</span><select className="select" name="type"><option value="concept">Concept</option><option value="mistake">Mistake</option><option value="solution">Problem</option><option value="design">Design</option><option value="question">Question</option><option value="insight">Insight</option></select></label><label className="field"><span>Title</span><input className="input" name="title" required/></label></div><label className="field"><span>Explain from memory / tradeoff / edge case</span><textarea className="textarea" name="content" required/></label><button className="btn btn-primary" disabled={add.isPending}><NotebookPen size={17}/>Save note</button></form><div className="row section" style={{flexWrap:'wrap'}}><div className="input-with-icon" style={{flex:1}}><Search size={17}/><input className="input" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search notebook"/></div><select className="select" style={{width:'auto'}} value={filter} onChange={(e)=>setFilter(e.target.value as typeof filter)}><option value="all">All</option><option value="concept">Concepts</option><option value="mistake">Mistakes</option><option value="solution">Problems</option><option value="design">Designs</option><option value="question">Questions</option></select></div><div className="plan-list section">{shown.map((note)=><article className="card card-pad" key={note.id}><div className="row-between"><span className="badge">{note.note_type}</span><button className="btn btn-ghost btn-icon" aria-label={`Delete ${note.title}`} onClick={()=>remove.mutate(note.id)}><Trash2 size={16}/></button></div><h3 style={{marginTop:12}}>{note.title}</h3><p className="small muted preserve-lines">{note.content}</p></article>)}{!shown.length&&<div className="empty-state">No matching notes yet.</div>}</div></section>
}

function Resources(){const resources=useResources();const [importMessage,setImportMessage]=useState('');return <section className="section"><div className="section-title"><h2>Recommended</h2><span className="badge">Curated by Dayframe</span></div><div className="grid-2">{(resources.data??[]).map((resource)=><article className="card card-pad" key={String(resource.id??resource.url??resource.title)}><Library size={20}/><h3 style={{marginTop:12}}>{String(resource.title)}</h3><p className="muted small">{String(resource.provider??resource.author_or_org??'Public reference')}</p>{resource.url&&<a className="btn btn-secondary btn-small" href={String(resource.url)} target="_blank" rel="noreferrer">Open source <ExternalLink size={14}/></a>}</article>)}</div><section className="card card-pad section"><p className="eyebrow">Import my plan</p><h2>Review before anything becomes active.</h2><p className="muted small">PDF, DOCX, TXT, Markdown and images are accepted by the secure import architecture. No parsing provider is configured in this deployment, so automatic extraction is currently unavailable and nothing will be uploaded or saved.</p><label className="btn btn-secondary"><FileUp size={16}/>Select document<input hidden type="file" accept=".pdf,.docx,.txt,.md,image/*" onChange={(e)=>{const file=e.target.files?.[0];if(file)setImportMessage(`${file.name} selected. Automatic parsing is unavailable until a server-side provider is configured.`)}}/></label>{importMessage&&<p className="auth-message">{importMessage}</p>}</section><p className="tiny muted section">Dayframe is not affiliated with or endorsed by these sources. LeetCode links are manual; Dayframe does not scrape or automatically sync profiles.</p></section>}
