import { useState } from 'react'
import { addDays, format, isSameDay, startOfWeek } from 'date-fns'
import { ArrowRight, BedDouble, BookOpen, CalendarDays, Check, ChevronLeft, ChevronRight, Droplets, Dumbbell, Footprints, HeartPulse, Share2, Utensils } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { useData } from '../context/DataContext'
import { useDayTravelItems, useNutritionSummary, usePlannedSessions, usePlans, useReviews } from '../hooks/useV2'
import { dateKey, nutritionTotal } from '../lib/v2'
import { usePersonalization } from '../hooks/usePersonalization'
import { focusCategories } from '../lib/personalization'
import { InterviewTodaySummary } from '../components/InterviewStudyOS'
import { isInterviewRoadmap } from '../lib/interview'
import { buildDayExport } from '../lib/dayExport'
import { DayExportSheet } from '../components/DayExportSheet'

export function TodayPage(){
  const[exportOpen,setExportOpen]=useState(false);const data=useData();const navigate=useNavigate();const date=data.selectedDate;const key=dateKey(date);const start=dateKey(startOfWeek(date,{weekStartsOn:1}));const end=dateKey(addDays(new Date(`${start}T12:00:00`),6))
  const planned=usePlannedSessions(key,key);const upcomingWorkouts=usePlannedSessions(key,dateKey(addDays(date,90)),'train');const travel=useDayTravelItems(key);const reviews=useReviews(key,key);const summary=useNutritionSummary(key);const personalization=usePersonalization();const studyPlans=usePlans('study');const roadmapSessions=usePlannedSessions(dateKey(addDays(date,-365)),dateKey(addDays(date,365)),'study')
  const workoutToday=planned.data?.find((item)=>item.domain==='train'&&['planned','active'].includes(item.status));const nextWorkout=(upcomingWorkouts.data??[]).find((item)=>['planned','active'].includes(item.status));const workout=workoutToday??nextWorkout;const dayExport=buildDayExport(key,planned.data??[],travel.data??[],workoutToday?undefined:nextWorkout)
  const study=planned.data?.find((item)=>item.domain==='study');const nutrition=nutritionTotal(summary.data,data.meals.map((meal)=>({...meal,fiber:0})))
  const activeStudyPlan=studyPlans.data?.find((item)=>item.status==='active')??studyPlans.data?.find((item)=>item.status==='paused');const activeStudySessions=(roadmapSessions.data??[]).filter((item)=>item.plan_id===activeStudyPlan?.id);const interviewMode=isInterviewRoadmap(activeStudyPlan,activeStudySessions)
  const reminders=data.reminders.filter((item)=>!item.completed).slice(0,3)
  return <div className="page">
    <header className="page-header"><div><p className="eyebrow">{format(date,'EEEE, MMMM d')}</p><h1>{isSameDay(date,new Date())?'Today, clearly.':'Your day in context.'}</h1><p className="muted">The parts of your life that matter now, placed first.</p></div><button className="btn btn-secondary btn-icon" aria-label="Export selected day" onClick={()=>setExportOpen(true)}><Share2 size={19}/></button></header>
    <CalendarStrip date={date} onChange={data.setSelectedDate}/>
    {(planned.error||upcomingWorkouts.error||summary.error)&&<div className="auth-message section"><strong>V2 database update needed.</strong><br/><span className="small">Apply migrations 202608220002 and 202608220003 in Supabase, then reload. Existing V1 data remains safe.</span></div>}
    {interviewMode&&<section className="section"><InterviewTodaySummary sessions={activeStudySessions} selectedDate={key} onOpen={()=>navigate('/study')}/></section>}
    <div className="today-focus-grid section">{focusCategories(personalization.interests).map((category) => category === 'Workouts'
      ? <FocusCard key={category} icon={<Dumbbell size={20}/>} label="Workouts" title={workout?.title??'No workout scheduled'} detail={workout?`${workoutToday?'Today':`Next workout · ${format(new Date(`${workout.scheduled_date}T12:00:00`),'EEE, MMM d')}`} · ${workout.estimated_minutes??60} min · ${workout.status.replace('_',' ')}`:'Choose or schedule a program in Workouts.'} action={workout?.status==='active'?'Resume':'Open Workouts'} onClick={()=>navigate('/train')}/>
      : category === 'Study' ? <FocusCard key={category} icon={<BookOpen size={20}/>} label="Study" title={study?.title??'No study session scheduled'} detail={study?`${study.estimated_minutes??60} min · ${study.planned_items?.length??0} tasks${reviews.data?.length?` · ${reviews.data.length} review due`:''}`:'Choose a roadmap or plan the next block.'} action={study?.status==='active'?'Resume':'Open Study'} onClick={()=>navigate('/study')}/>
      : category === 'Health' ? <FocusCard key={category} icon={<HeartPulse size={20}/>} label="Health" title={nutrition.calories ? `${Math.round(nutrition.calories)} kcal logged` : 'Build today’s health context'} detail={`${data.daily.steps.toLocaleString()} steps · ${data.daily.sleepHours ? `${data.daily.sleepHours.toFixed(1)} h sleep` : 'sleep not logged'}`} action="Open Nutrition" onClick={()=>navigate('/nutrition')}/>
      : <FocusCard key={category} icon={<CalendarDays size={20}/>} label="Life" title={reminders.length ? `${reminders.length} open reminder${reminders.length === 1 ? '' : 's'}` : 'Your day is clear'} detail="Keep goals, reminders and plans in one place." action="Open Life" onClick={()=>navigate('/life')}/>)}</div>
    <section className="section"><div className="section-title"><h2>Health context</h2><div className="row section-links"><button className="link-button small section-link" onClick={()=>navigate('/nutrition')}>Nutrition <ArrowRight size={14}/></button><button className="link-button small section-link" onClick={()=>navigate('/health')}>Health <ArrowRight size={14}/></button></div></div><div className="card card-pad compact-health">
      <MiniMetric icon={<BedDouble/>} value={data.daily.sleepHours?`${data.daily.sleepHours.toFixed(1)} h`:'—'} label="sleep"/><MiniMetric icon={<Footprints/>} value={data.daily.steps.toLocaleString()} label="steps"/><MiniMetric icon={<Droplets/>} value={`${data.daily.waterMl} ml`} label="water"/><MiniMetric icon={<Utensils/>} value={nutrition.calories?`${Math.round(nutrition.calories)}`:'—'} label={nutrition.source==='summary'?'kcal · summary':'kcal · itemized'}/>
    </div></section>
    <section className="section"><div className="section-title"><h2>Life reminders</h2><button className="link-button small section-link" onClick={()=>navigate('/life')}>Open Life <ArrowRight size={14}/></button></div><div className="card card-pad">{reminders.length?reminders.map((item)=><button className="reminder-row" key={item.id} onClick={()=>data.toggleReminder(item.id)}><span className={`check ${item.completed?'checked':''}`}>{item.completed&&<Check size={14}/>}</span><span><strong>{item.title}</strong><span className="tiny muted">{item.time??item.category}</span></span></button>):<div className="empty-state"><HeartPulse size={24}/><p>No open reminders for this day.</p></div>}</div></section>
    <p className="small muted section week-context-note">Week shown: {format(new Date(`${start}T12:00:00`),'MMM d')}–{format(new Date(`${end}T12:00:00`),'MMM d')}. Historical dates remain editable from the strip above.</p>
    <DayExportSheet open={exportOpen} onClose={()=>setExportOpen(false)} value={dayExport}/>
  </div>
}
function FocusCard({icon,label,title,detail,action,onClick}:{icon:React.ReactNode;label:string;title:string;detail:string;action:string;onClick:()=>void}){return <article className="card focus-card"><div><span className="icon-bubble">{icon}</span></div><div><p className="eyebrow">{label}</p><h2>{title}</h2><p className="muted small">{detail}</p></div><button className="btn btn-primary" onClick={onClick}>{action}<ArrowRight size={16}/></button></article>}
function MiniMetric({icon,value,label}:{icon:React.ReactNode;value:string;label:string}){return <div className="mini-metric"><span>{icon}</span><strong>{value}</strong><small>{label}</small></div>}
function CalendarStrip({date,onChange}:{date:Date;onChange:(date:Date)=>void}){const start=startOfWeek(date,{weekStartsOn:1});return <div className="calendar-navigation"><button className="btn btn-secondary btn-icon calendar-nav-button" aria-label="Previous week" onClick={()=>onChange(addDays(date,-7))}><ChevronLeft/></button><div className="calendar-strip">{Array.from({length:7},(_,index)=>addDays(start,index)).map((day)=><button className={`calendar-day ${isSameDay(day,date)?'active':''}`} key={day.toISOString()} onClick={()=>onChange(day)}><span className="tiny">{format(day,'EEE')}</span><strong>{format(day,'d')}</strong></button>)}</div><button className="btn btn-secondary btn-icon calendar-nav-button" aria-label="Next week" onClick={()=>onChange(addDays(date,7))}><ChevronRight/></button></div>}
