import { useEffect, useState } from 'react'
import { addDays, format, subYears } from 'date-fns'
import { Check, Clock3, Dumbbell, History, Pause, Play, Plus, RotateCcw, Sparkles, TrendingUp } from 'lucide-react'
import { useData } from '../context/DataContext'
import { useCopyTemplate, useIdentity, usePlans, usePlannedSessions, useProgressData, useTemplates, useV2Mutation } from '../hooks/useV2'
import { dateKey, progressionSuggestion } from '../lib/v2'
import { updatePlan, updatePlannedSession } from '../repositories/v2Repository'
import type { PlannedSession, PlanTemplate } from '../types/v2'

type View='today'|'program'|'history'|'templates'
export function TrainPage(){const[view,setView]=useState<View>('today');const[active,setActive]=useState<PlannedSession|null>(null);const data=useData();const today=dateKey(data.selectedDate);const end=dateKey(addDays(data.selectedDate,90));const plans=usePlans('train');const scheduled=usePlannedSessions(today,end,'train');const plan=plans.data?.find((item)=>item.status==='active');const next=scheduled.data?.find((item)=>['planned','active'].includes(item.status))
  const begin=async(session:PlannedSession)=>{await data.loadWorkoutFromPlan((session.planned_items??[]).map((item)=>({id:item.id,title:item.title,metadata:item.metadata})));setActive(session)}
  return <div className="page"><header className="page-header"><div><p className="eyebrow">Train</p><h1>Strong, one set at a time.</h1><p className="muted">Your schedule, execution, history and curated programs.</p></div></header>{!active&&<div className="tabs">{(['today','program','history','templates']as View[]).map((item)=><button className={`tab ${view===item?'active':''}`} key={item} onClick={()=>setView(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div>}
    {active?<WorkoutLogger planned={active} onDone={()=>setActive(null)}/>:<>{view==='today'&&<TrainToday plan={plan} next={next} onStart={(session)=>void begin(session)}/>} {view==='program'&&<Program plan={plan} sessions={scheduled.data??[]}/>} {view==='history'&&<TrainHistory/>} {view==='templates'&&<TrainTemplates/>}</>}
  </div>}

function TrainToday({plan,next,onStart}:{plan?:{name:string};next?:PlannedSession;onStart:(session:PlannedSession)=>void}){if(!plan)return <section className="card card-pad section empty-state"><Dumbbell size={28}/><h2>No active training plan</h2><p>Open Templates and explicitly copy a program that fits your week.</p></section>;return <><section className="card today-hero section"><div className="row-between"><span className="badge" style={{background:'rgba(245,240,231,.13)',color:'#F5F0E7'}}>{plan.name}</span>{next&&<span className="small muted">{format(new Date(`${next.scheduled_date}T12:00:00`),'EEE, MMM d')}</span>}</div><div className="hero-workout"><div><p className="muted small">{next?.scheduled_date===dateKey()?'Today':'Up next'}</p><h2>{next?.title??'Nothing scheduled'}</h2><p className="muted small">{next?`${next.estimated_minutes??60} min · ${next.planned_items?.length??0} exercises`:'Review your program schedule.'}</p></div>{next&&<button className="btn btn-primary" onClick={()=>onStart(next)}><Play size={17}/> {next.status==='active'?'Resume':'Start'}</button>}</div></section>{next&&<section className="section"><div className="section-title"><h2>Session prescription</h2><span className="badge">persisted schedule</span></div><div className="card card-pad">{next.planned_items?.map((item)=><div className="meal-row" key={item.id}><div><strong>{item.title}</strong><div className="tiny muted">{Number(item.metadata.sets??3)} sets · {Number(item.metadata.rep_min??8)}–{Number(item.metadata.rep_max??12)} reps</div></div><span className="badge badge-neutral">{item.status}</span></div>)}</div></section>}</>}

function Program({plan,sessions}:{plan?:{id:string;name:string;goal?:string|null;status:string;start_date?:string|null;target_date?:string|null};sessions:PlannedSession[]}){const identity=useIdentity();const change=useV2Mutation((_identity:typeof identity,input:{status:'paused'|'active'|'archived'})=>plan?updatePlan(_identity,plan.id,{status:input.status}):Promise.resolve());void identity;if(!plan)return <div className="empty-state section">No active program.</div>;return <section className="section"><article className="card card-pad"><div className="row-between"><div><p className="eyebrow">Active personal copy</p><h2>{plan.name}</h2></div><span className="badge">{plan.status}</span></div><p className="muted small">{plan.goal} · {plan.start_date??'No start'} to {plan.target_date??'open ended'}</p><div className="row"><button className="btn btn-secondary btn-small" onClick={()=>change.mutate({status:plan.status==='paused'?'active':'paused'})}>{plan.status==='paused'?'Resume plan':'Pause plan'}</button><button className="btn btn-ghost btn-small" onClick={()=>change.mutate({status:'archived'})}>Archive</button></div><p className="tiny muted section">Edits affect only your copy; published template versions remain immutable.</p></article><div className="plan-list section">{sessions.slice(0,14).map((item)=><article className="card card-pad row-between" key={item.id}><div><span className="tiny muted">{format(new Date(`${item.scheduled_date}T12:00:00`),'EEE, MMM d')}</span><h3>{item.title}</h3></div><span className="badge badge-neutral">{item.status.replace('_',' ')}</span></article>)}</div></section>}

function TrainHistory(){const from=dateKey(subYears(new Date(),1));const to=dateKey();const progress=useProgressData(from,to);const workouts=progress.data?.workouts??[];return <section className="section"><div className="grid-3"><Metric value={String(workouts.filter((item)=>item.status==='completed').length)} label="completed workouts"/><Metric value={String(progress.data?.sets.filter((item)=>item.completed).length??0)} label="completed sets"/><Metric value={workouts.length?`${Math.round(workouts.filter((item)=>item.status==='completed').length/workouts.length*100)}%`:'—'} label="completion rate"/></div><div className="section-title" style={{marginTop:26}}><h2>Recent sessions</h2><History size={18}/></div><div className="card card-pad">{workouts.length?workouts.slice(0,12).map((item)=><div className="meal-row" key={item.id}><div><strong>{format(new Date(`${item.session_date}T12:00:00`),'MMM d, yyyy')}</strong><div className="tiny muted">{item.status} · {item.exercise_logs?.length??0} exercises</div></div><span className="badge badge-neutral">persisted</span></div>):<div className="empty-state">No completed workouts in this range. Dayframe does not invent history.</div>}</div></section>}

function TrainTemplates(){const templates=useTemplates('train');const copy=useCopyTemplate();const[startDate,setStartDate]=useState(dateKey());const[preview,setPreview]=useState<PlanTemplate|null>(null);const[days,setDays]=useState(4);const shown=(templates.data??[]).sort((a,b)=>(a.version.days_per_week_min??0)-(b.version.days_per_week_min??0));return <section className="section"><article className="card card-pad"><p className="eyebrow">Recommendation filter</p><div className="grid-2"><label className="field"><span>Days available: {days}</span><input type="range" min="1" max="7" value={days} onChange={(e)=>setDays(Number(e.target.value))}/></label><label className="field"><span>Start date</span><input className="input" type="date" value={startDate} onChange={(e)=>setStartDate(e.target.value)}/></label></div><p className="muted small">Availability filters the catalog. You choose and confirm the final copy.</p></article><div className="grid-2 section">{shown.map((template)=><article className={`card card-pad ${template.version.days_per_week_min===days?'recommended-card':''}`} key={template.id}><div className="row-between"><span className="badge">{template.version.days_per_week_min} day{template.version.days_per_week_min===1?'':'s'}</span>{template.featured&&<span className="tiny muted">Featured</span>}</div><h2 style={{marginTop:14}}>{template.name}</h2><p className="muted small">{template.short_description}</p><button className="btn btn-secondary" onClick={()=>setPreview(template)}>Preview</button></article>)}</div>{preview&&<article className="card card-pad section"><div className="row-between"><div><p className="eyebrow">Science-informed Dayframe template · v{preview.version.version}</p><h2>{preview.name}</h2></div><button className="btn btn-ghost" onClick={()=>setPreview(null)}>Close</button></div><p className="muted">{preview.short_description}</p>{preview.version.content.phases.flatMap((phase)=>phase.blocks).flatMap((block)=>block.sessions).map((session)=><div className="meal-row" key={session.title}><div><strong>{session.title}</strong><div className="tiny muted">{session.items.length} movements · {session.minutes} min</div></div></div>)}<button className="btn btn-primary section" disabled={copy.isPending} onClick={()=>copy.mutate({template:preview,startDate})}><Plus size={16}/>{copy.isPending?'Copying…':'Copy template'}</button>{copy.isSuccess&&<p className="auth-message">Your normalized plan and scheduled sessions are ready.</p>}{copy.error&&<p className="field-error">{copy.error.message}</p>}<p className="tiny muted section">Curated by Dayframe. Dayframe is not affiliated with or endorsed by external sources.</p></article>}</section>}

function WorkoutLogger({planned,onDone}:{planned:PlannedSession;onDone:()=>void}){const data=useData();const identity=useIdentity();const completePlan=useV2Mutation((_identity:typeof identity,id:string)=>updatePlannedSession(_identity,id,{status:'completed',completed_at:new Date().toISOString()}));const[elapsed,setElapsed]=useState(0);const[rest,setRest]=useState(0);const[running,setRunning]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const total=data.workout.reduce((sum,item)=>sum+item.sets.length,0);const done=data.workout.reduce((sum,item)=>sum+item.sets.filter((set)=>set.completed).length,0);useEffect(()=>{const id=window.setInterval(()=>setElapsed((v)=>v+1),1000);return()=>window.clearInterval(id)},[]);useEffect(()=>{if(!running||rest<=0)return;const id=window.setInterval(()=>setRest((v)=>{if(v<=1){setRunning(false);return 0}return v-1}),1000);return()=>window.clearInterval(id)},[running,rest]);const finish=async()=>{setSaving(true);setError('');try{await data.saveWorkout(planned.id);await completePlan.mutateAsync(planned.id);onDone()}catch(e){setError(e instanceof Error?e.message:'Workout could not be saved')}finally{setSaving(false)}}
  void identity
  return <section className="section"><div className="rest-timer"><div className="row"><Clock3/><div><strong>{rest?`Rest ${Math.floor(rest/60)}:${String(rest%60).padStart(2,'0')}`:`Session ${Math.floor(elapsed/60)}:${String(elapsed%60).padStart(2,'0')}`}</strong><div className="tiny">{done}/{total} sets</div></div></div>{rest>0&&<div className="row"><button className="btn btn-ghost btn-icon" style={{color:'inherit'}} onClick={()=>setRunning(!running)}>{running?<Pause/>:<Play/>}</button><button className="btn btn-ghost btn-icon" style={{color:'inherit'}} onClick={()=>{setRest(90);setRunning(true)}}><RotateCcw/></button></div>}</div><p className="eyebrow">Active workout</p><h1>{planned.title}</h1><div className="progress-track"><div className="progress-fill" style={{width:`${total?done/total*100:0}%`}}/></div><div className="plan-list section">{data.workout.map((exercise,index)=><article className="card workout-card" key={exercise.id}><span className="tiny muted">{index+1} · {exercise.repRange}</span><h2>{exercise.name}</h2><p className="tiny muted">Previous: {exercise.previous}</p><table className="set-table"><thead><tr><th>Set</th><th>kg</th><th>Reps</th><th>RIR</th><th>Done</th></tr></thead><tbody>{exercise.sets.map((set,i)=><tr key={set.id}><td>{i+1}</td><td><input className="set-input" aria-label={`${exercise.name} set ${i+1} weight`} type="number" step="0.5" value={set.weight} onChange={(e)=>data.updateSet(exercise.id,set.id,'weight',Number(e.target.value))}/></td><td><input className="set-input" aria-label={`${exercise.name} set ${i+1} reps`} type="number" value={set.reps||''} onChange={(e)=>data.updateSet(exercise.id,set.id,'reps',Number(e.target.value))}/></td><td><input className="set-input" aria-label={`${exercise.name} set ${i+1} RIR`} type="number" min="0" max="10" value={set.rir} onChange={(e)=>data.updateSet(exercise.id,set.id,'rir',Number(e.target.value))}/></td><td><button className={`check ${set.completed?'checked':''}`} aria-label={`Mark ${exercise.name} set ${i+1} ${set.completed?'incomplete':'complete'}`} onClick={()=>{data.updateSet(exercise.id,set.id,'completed',!set.completed);if(!set.completed){setRest(90);setRunning(true)}}}>{set.completed&&<Check size={15}/>}</button></td></tr>)}</tbody></table>{progressionSuggestion(exercise.sets,Number(exercise.repRange.match(/–(\d+)/)?.[1]??12))&&<div className="insight-callout small"><Sparkles size={15}/> {progressionSuggestion(exercise.sets,Number(exercise.repRange.match(/–(\d+)/)?.[1]??12))} Confirm before changing the next prescription.</div>}</article>)}</div><button className="btn btn-primary section" disabled={!done||saving} onClick={()=>void finish()}>{saving?'Saving persisted workout…':'Finish workout'}</button>{error&&<p className="field-error">{error}</p>}</section>}
function Metric({value,label}:{value:string;label:string}){return <article className="card card-pad"><span className="icon-bubble"><TrendingUp/></span><span className="metric-value" style={{marginTop:14}}>{value}</span><span className="metric-label">{label}</span></article>}
