import { useEffect, useState, type FormEvent } from 'react'
import { addDays, format, subYears } from 'date-fns'
import { Check, Clock3, Dumbbell, History, Pause, Play, Plus, RotateCcw, Sparkles, TrendingUp } from 'lucide-react'
import { TemplateGuide } from '../components/TemplateGuide'
import { useData } from '../context/DataContext'
import { useCopyTemplate, useIdentity, usePlans, usePlannedSessions, useProgressData, useTemplates, useV2Mutation } from '../hooks/useV2'
import { dateKey, progressionSuggestion } from '../lib/v2'
import { resetDomainPlans, updatePlan, updatePlannedSession } from '../repositories/v2Repository'
import type { PlannedSession, PlanTemplate } from '../types/v2'
import { usePersonalization } from '../hooks/usePersonalization'

type View='today'|'program'|'history'|'templates'
export function TrainPage(){const[view,setView]=useState<View>('templates');const[active,setActive]=useState<PlannedSession|null>(null);const data=useData();const today=dateKey(data.selectedDate);const end=dateKey(addDays(data.selectedDate,90));const plans=usePlans('train');const scheduled=usePlannedSessions(today,end,'train');const plan=plans.data?.find((item)=>item.status==='active')??plans.data?.find((item)=>item.status==='paused');const planSessions=(scheduled.data??[]).filter((item)=>item.plan_id===plan?.id);const next=planSessions.find((item)=>['planned','active'].includes(item.status));const currentView=plan&&view==='templates'?'today':view
  const begin=async(session:PlannedSession)=>{await data.loadWorkoutFromPlan((session.planned_items??[]).map((item)=>({id:item.id,title:item.title,metadata:item.metadata})));setActive(session)}
  const tabs:View[]=plan?['today','program','history']:['templates','today','program','history']
  return <div className="page"><header className="page-header"><div><p className="eyebrow">Train</p><h1>Strong, one set at a time.</h1><p className="muted">Your schedule, execution, history and curated programs.</p></div></header>{!active&&<div className="tabs">{tabs.map((item)=><button className={`tab ${currentView===item?'active':''}`} key={item} onClick={()=>setView(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div>}
    {active?<WorkoutLogger planned={active} onDone={()=>setActive(null)}/>:<>{currentView==='today'&&<TrainToday plan={plan} next={next} onStart={(session)=>void begin(session)}/>} {currentView==='program'&&<Program plan={plan} sessions={planSessions} onReset={()=>setView('templates')}/>} {currentView==='history'&&<TrainHistory/>} {currentView==='templates'&&!plan&&<TrainTemplates/>}</>}
  </div>}

interface TrainSetupValues { goal:string;experience:string;days:number;equipment:string;limitations:string }
function TrainSetup({onSaved}:{onSaved:(values:TrainSetupValues)=>void}){const personalization=usePersonalization();const setup=personalization.getDomainSetup('train');const[saving,setSaving]=useState(false);const[error,setError]=useState('');const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);setError('');const form=new FormData(event.currentTarget);const values={goal:String(form.get('goal')),experience:String(form.get('experience')),days:Number(form.get('days')),equipment:String(form.get('equipment')),limitations:String(form.get('limitations')??'')};try{await personalization.saveDomainSetup('train',values);onSaved(values)}catch(value){setError(value instanceof Error?value.message:'Training preferences could not be saved.')}finally{setSaving(false)}};return <section className="card card-pad section progressive-setup"><p className="eyebrow">{setup?'Your training preferences':'First, personalize the catalog'}</p><h2>Make the program fit your real week.</h2><p className="muted small">These answers rank the catalog; they never select a program without your confirmation. You can update them before copying.</p><form className="form-grid section" onSubmit={submit}><div className="grid-2"><label className="field"><span>Main goal</span><select className="select" name="goal" defaultValue={String(setup?.goal??'Build muscle')}><option>Build strength</option><option>Build muscle</option><option>Improve endurance</option><option>General fitness</option></select></label><label className="field"><span>Experience</span><select className="select" name="experience" defaultValue={String(setup?.experience??'New to structured training')}><option>New to structured training</option><option>Some experience</option><option>Experienced</option></select></label><label className="field"><span>Days available each week</span><input className="input" name="days" type="number" min="1" max="7" defaultValue={Number(setup?.days)||3} required/></label><label className="field"><span>Equipment</span><select className="select" name="equipment" defaultValue={String(setup?.equipment??'Full gym')}><option>Full gym</option><option>Home gym</option><option>Dumbbells / bands</option><option>Bodyweight only</option></select></label></div><label className="field"><span>Limitations to account for (optional)</span><textarea className="textarea" name="limitations" defaultValue={String(setup?.limitations??'')} placeholder="Injuries, movements to avoid, or accessibility needs"/></label>{error&&<p className="field-error">{error}</p>}<div className="row progressive-actions"><button className="btn btn-primary" disabled={saving}>{saving?'Saving…':setup?'Update recommendations':'Save and rank programs'}</button>{!setup&&<button className="btn btn-ghost" type="button" onClick={()=>void personalization.skipDomainSetup('train')}>Skip for now</button>}</div></form></section>}

function TrainToday({plan,next,onStart}:{plan?:{name:string};next?:PlannedSession;onStart:(session:PlannedSession)=>void}){if(!plan)return <section className="card card-pad section empty-state"><Dumbbell size={28}/><h2>No active training plan</h2><p>Open Templates and explicitly copy a program that fits your week.</p></section>;return <><section className="card today-hero section"><div className="row-between"><span className="badge" style={{background:'rgba(245,240,231,.13)',color:'#F5F0E7'}}>{plan.name}</span>{next&&<span className="small muted">{format(new Date(`${next.scheduled_date}T12:00:00`),'EEE, MMM d')}</span>}</div><div className="hero-workout"><div><p className="muted small">{next?.scheduled_date===dateKey()?'Today':'Up next'}</p><h2>{next?.title??'Nothing scheduled'}</h2><p className="muted small">{next?`${next.estimated_minutes??60} min · ${next.planned_items?.length??0} exercises`:'Review your program schedule.'}</p></div>{next&&<button className="btn btn-primary" onClick={()=>onStart(next)}><Play size={17}/> {next.status==='active'?'Resume':'Start'}</button>}</div></section>{next&&<section className="section"><div className="section-title"><h2>Session prescription</h2><span className="badge">persisted schedule</span></div><div className="card card-pad">{next.planned_items?.map((item)=><div className="meal-row" key={item.id}><div><strong>{item.title}</strong><div className="tiny muted">{Number(item.metadata.sets??3)} sets · {Number(item.metadata.rep_min??8)}–{Number(item.metadata.rep_max??12)} reps</div></div><span className="badge badge-neutral">{item.status}</span></div>)}</div></section>}</>}

function Program({plan,sessions,onReset}:{plan?:{id:string;name:string;goal?:string|null;status:string;start_date?:string|null;target_date?:string|null};sessions:PlannedSession[];onReset:()=>void}){const identity=useIdentity();const[confirmReset,setConfirmReset]=useState(false);const change=useV2Mutation((_identity:typeof identity,input:{status:'paused'|'active'})=>plan?updatePlan(_identity,plan.id,{status:input.status}):Promise.resolve());const reset=useV2Mutation<void>((_identity)=>resetDomainPlans(_identity,'train'));void identity;if(!plan)return <div className="empty-state section">No active program. Open Templates to choose one.</div>;return <section className="section"><article className="card card-pad"><div className="row-between"><div><p className="eyebrow">Active personal copy</p><h2>{plan.name}</h2></div><span className="badge">{plan.status}</span></div><p className="muted small">{plan.goal} · {plan.start_date??'No start'} to {plan.target_date??'open ended'}</p><div className="row progressive-actions"><button className="btn btn-secondary btn-small" onClick={()=>change.mutate({status:plan.status==='paused'?'active':'paused'})}>{plan.status==='paused'?'Resume plan':'Pause plan'}</button><button className="btn btn-ghost btn-small" onClick={()=>setConfirmReset(true)}><RotateCcw size={15}/>Choose a different template</button></div><p className="tiny muted section">This is your editable copy; the published template stays unchanged.</p></article>{confirmReset&&<article className="card card-pad section reset-template-card"><p className="eyebrow">Reset active template?</p><h2>Your history stays safe.</h2><p className="muted small">Dayframe will archive this program and its remaining schedule, then show Templates again. Completed workouts and logged sets are not deleted.</p><div className="row progressive-actions"><button className="btn btn-primary" disabled={reset.isPending} onClick={()=>reset.mutate(undefined,{onSuccess:onReset})}>{reset.isPending?'Resetting…':'Archive and choose again'}</button><button className="btn btn-ghost" disabled={reset.isPending} onClick={()=>setConfirmReset(false)}>Keep current program</button></div>{reset.error&&<p className="field-error">{reset.error.message}</p>}</article>}<div className="plan-list section">{sessions.slice(0,14).map((item)=><article className="card card-pad row-between" key={item.id}><div><span className="tiny muted">{format(new Date(`${item.scheduled_date}T12:00:00`),'EEE, MMM d')}</span><h3>{item.title}</h3></div><span className="badge badge-neutral">{item.status.replace('_',' ')}</span></article>)}</div></section>}

function TrainHistory(){const from=dateKey(subYears(new Date(),1));const to=dateKey();const progress=useProgressData(from,to);const workouts=progress.data?.workouts??[];return <section className="section"><div className="grid-3"><Metric value={String(workouts.filter((item)=>item.status==='completed').length)} label="completed workouts"/><Metric value={String(progress.data?.sets.filter((item)=>item.completed).length??0)} label="completed sets"/><Metric value={workouts.length?`${Math.round(workouts.filter((item)=>item.status==='completed').length/workouts.length*100)}%`:'—'} label="completion rate"/></div><div className="section-title" style={{marginTop:26}}><h2>Recent sessions</h2><History size={18}/></div><div className="card card-pad">{workouts.length?workouts.slice(0,12).map((item)=><div className="meal-row" key={item.id}><div><strong>{format(new Date(`${item.session_date}T12:00:00`),'MMM d, yyyy')}</strong><div className="tiny muted">{item.status} · {item.exercise_logs?.length??0} exercises</div></div><span className="badge badge-neutral">persisted</span></div>):<div className="empty-state">No completed workouts in this range. Dayframe does not invent history.</div>}</div></section>}

function TrainTemplates(){
  const templates=useTemplates('train');const copy=useCopyTemplate();const personalization=usePersonalization();const setup=personalization.getDomainSetup('train');const[startDate,setStartDate]=useState(dateKey());const[preview,setPreview]=useState<PlanTemplate|null>(null);const[days,setDays]=useState(Number(setup?.days)||3)
  const distance=(template:PlanTemplate)=>{const min=template.version.days_per_week_min??1;const max=template.version.days_per_week_max??min;return days<min?min-days:days>max?days-max:0}
  const shown=[...(templates.data??[])].sort((a,b)=>distance(a)-distance(b)||Number(b.featured)-Number(a.featured)||(a.version.days_per_week_min??0)-(b.version.days_per_week_min??0))
  const togglePreview=(template:PlanTemplate)=>{copy.reset();setPreview((current)=>current?.id===template.id?null:template)}
  return <section className="section">
    <TemplateGuide domain="train"/>
    <TrainSetup onSaved={(values)=>setDays(values.days)}/>
    <article className="card card-pad section"><p className="eyebrow">Ranked recommendations</p><div className="grid-2"><label className="field"><span>Compare programs for {days} day{days===1?'':'s'} per week</span><input aria-label="Training days to compare" type="range" min="1" max="7" value={days} onChange={(e)=>setDays(Number(e.target.value))}/></label><label className="field"><span>Start date</span><input className="input" type="date" value={startDate} onChange={(e)=>setStartDate(e.target.value)}/></label></div><p className="muted small">Exact {days}-day programs appear first, followed by the closest practical alternatives. You still preview and confirm the copy.</p></article>
    <div className="grid-2 section">{shown.map((template,index)=>{const expanded=preview?.id===template.id;const exact=distance(template)===0;return <article className={`card card-pad ${exact?'recommended-card':''}`} key={template.id}>
      <div className="row-between"><span className="badge">{template.version.days_per_week_min} day{template.version.days_per_week_min===1?'':'s'}</span>{exact&&index===0?<span className="badge">Best match</span>:template.featured&&<span className="tiny muted">Featured</span>}</div><h2 style={{marginTop:14}}>{template.name}</h2><p className="muted small">{template.short_description}</p><button className="btn btn-secondary" aria-expanded={expanded} onClick={()=>togglePreview(template)}>{expanded?'Hide details':'Preview program'}</button>
      {expanded&&<div className="template-inline-preview"><div className="row-between"><p className="eyebrow">Science-informed · v{template.version.version}</p><button className="btn btn-ghost btn-small" onClick={()=>setPreview(null)}>Close</button></div>{template.version.content.phases.flatMap((phase)=>phase.blocks).flatMap((block)=>block.sessions).map((session)=><div className="meal-row" key={session.title}><div><strong>{session.title}</strong><div className="tiny muted">{session.items.length} movements · {session.minutes} min</div></div></div>)}<button className="btn btn-primary section" disabled={copy.isPending} onClick={()=>copy.mutate({template,startDate})}><Plus size={16}/>{copy.isPending?'Copying…':'Copy template'}</button>{copy.isSuccess&&<p className="auth-message">Your normalized plan and scheduled sessions are ready.</p>}{copy.error&&<p className="field-error">{copy.error.message}</p>}<p className="tiny muted section">Curated by Dayframe. Dayframe is not affiliated with or endorsed by external sources.</p></div>}
    </article>})}</div>
  </section>
}

function WorkoutLogger({planned,onDone}:{planned:PlannedSession;onDone:()=>void}){const data=useData();const identity=useIdentity();const completePlan=useV2Mutation((_identity:typeof identity,id:string)=>updatePlannedSession(_identity,id,{status:'completed',completed_at:new Date().toISOString()}));const[elapsed,setElapsed]=useState(0);const[rest,setRest]=useState(0);const[running,setRunning]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const total=data.workout.reduce((sum,item)=>sum+item.sets.length,0);const done=data.workout.reduce((sum,item)=>sum+item.sets.filter((set)=>set.completed).length,0);useEffect(()=>{const id=window.setInterval(()=>setElapsed((v)=>v+1),1000);return()=>window.clearInterval(id)},[]);useEffect(()=>{if(!running||rest<=0)return;const id=window.setInterval(()=>setRest((v)=>{if(v<=1){setRunning(false);return 0}return v-1}),1000);return()=>window.clearInterval(id)},[running,rest]);const finish=async()=>{setSaving(true);setError('');try{await data.saveWorkout(planned.id);await completePlan.mutateAsync(planned.id);onDone()}catch(e){setError(e instanceof Error?e.message:'Workout could not be saved')}finally{setSaving(false)}}
  void identity
  return <section className="section"><div className="rest-timer"><div className="row"><Clock3/><div><strong>{rest?`Rest ${Math.floor(rest/60)}:${String(rest%60).padStart(2,'0')}`:`Session ${Math.floor(elapsed/60)}:${String(elapsed%60).padStart(2,'0')}`}</strong><div className="tiny">{done}/{total} sets</div></div></div>{rest>0&&<div className="row"><button className="btn btn-ghost btn-icon" style={{color:'inherit'}} onClick={()=>setRunning(!running)}>{running?<Pause/>:<Play/>}</button><button className="btn btn-ghost btn-icon" style={{color:'inherit'}} onClick={()=>{setRest(90);setRunning(true)}}><RotateCcw/></button></div>}</div><p className="eyebrow">Active workout</p><h1>{planned.title}</h1><div className="progress-track"><div className="progress-fill" style={{width:`${total?done/total*100:0}%`}}/></div><div className="plan-list section">{data.workout.map((exercise,index)=><article className="card workout-card" key={exercise.id}><span className="tiny muted">{index+1} · {exercise.repRange}</span><h2>{exercise.name}</h2><p className="tiny muted">Previous: {exercise.previous}</p><table className="set-table"><thead><tr><th>Set</th><th>kg</th><th>Reps</th><th>RIR</th><th>Done</th></tr></thead><tbody>{exercise.sets.map((set,i)=><tr key={set.id}><td>{i+1}</td><td><input className="set-input" aria-label={`${exercise.name} set ${i+1} weight`} type="number" step="0.5" value={set.weight} onChange={(e)=>data.updateSet(exercise.id,set.id,'weight',Number(e.target.value))}/></td><td><input className="set-input" aria-label={`${exercise.name} set ${i+1} reps`} type="number" value={set.reps||''} onChange={(e)=>data.updateSet(exercise.id,set.id,'reps',Number(e.target.value))}/></td><td><input className="set-input" aria-label={`${exercise.name} set ${i+1} RIR`} type="number" min="0" max="10" value={set.rir} onChange={(e)=>data.updateSet(exercise.id,set.id,'rir',Number(e.target.value))}/></td><td><button className={`check ${set.completed?'checked':''}`} aria-label={`Mark ${exercise.name} set ${i+1} ${set.completed?'incomplete':'complete'}`} onClick={()=>{data.updateSet(exercise.id,set.id,'completed',!set.completed);if(!set.completed){setRest(90);setRunning(true)}}}>{set.completed&&<Check size={15}/>}</button></td></tr>)}</tbody></table>{progressionSuggestion(exercise.sets,Number(exercise.repRange.match(/–(\d+)/)?.[1]??12))&&<div className="insight-callout small"><Sparkles size={15}/> {progressionSuggestion(exercise.sets,Number(exercise.repRange.match(/–(\d+)/)?.[1]??12))} Confirm before changing the next prescription.</div>}</article>)}</div><button className="btn btn-primary section" disabled={!done||saving} onClick={()=>void finish()}>{saving?'Saving persisted workout…':'Finish workout'}</button>{error&&<p className="field-error">{error}</p>}</section>}
function Metric({value,label}:{value:string;label:string}){return <article className="card card-pad"><span className="icon-bubble"><TrendingUp/></span><span className="metric-value" style={{marginTop:14}}>{value}</span><span className="metric-label">{label}</span></article>}
