import { useState } from 'react'
import { Bell, Check, Clipboard, ExternalLink, NotebookPen, Share2 } from 'lucide-react'
import { Sheet } from './Sheet'
import type { DayExport, DayExportCategory } from '../lib/dayExport'

const shortcutName='Dayframe to Reminders'

export function DayExportSheet({open,onClose,value}:{open:boolean;onClose:()=>void;value:DayExport}){
  const[showSetup,setShowSetup]=useState(false);const[confirmReset,setConfirmReset]=useState(false);const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);const[shortcutReady,setShortcutReady]=useState(()=>localStorage.getItem('dayframe_reminders_shortcut_ready')==='true')
  const exportedKey=`dayframe_reminders_export_${value.date}`;const exportedBefore=localStorage.getItem(exportedKey)==='true';const empty=!value.items.length
  const share=async(target:'notes'|'reminders')=>{setBusy(true);setMessage('');try{if(navigator.share){await navigator.share({title:value.title,text:value.noteText,url:window.location.href});setMessage(target==='notes'?'Shared. Choose Notes and its destination folder in Apple’s sheet.':'Shared as one day summary. Choose Reminders in Apple’s sheet.')}else{await copyText(value.noteText);setMessage('Sharing is unavailable here, so the checklist was copied.')}}catch(error){if(error instanceof DOMException&&error.name==='AbortError')return;setMessage('The share sheet could not open. The checklist is still available to copy.')}finally{setBusy(false)}}
  const runShortcut=()=>{if(!shortcutReady){setShowSetup(true);return}setMessage('');localStorage.setItem(exportedKey,'true');window.location.href=`shortcuts://run-shortcut?name=${encodeURIComponent(shortcutName)}&input=text&text=${encodeURIComponent(value.reminderPayload)}`;setMessage('Sent to the Dayframe Reminders shortcut.')}
  const copy=async()=>{try{await copyText(value.noteText);setMessage('Today’s checklist copied.')}catch{setMessage('Your browser blocked clipboard access.')}}
  const resetShortcut=()=>{for(let index=localStorage.length-1;index>=0;index--){const key=localStorage.key(index);if(key?.startsWith('dayframe_reminders_export_'))localStorage.removeItem(key)}localStorage.removeItem('dayframe_reminders_shortcut_ready');setShortcutReady(false);setConfirmReset(false);setShowSetup(true);setMessage('Shortcut setup reset in Dayframe. Recreate it below; remove the old Shortcut separately in Apple Shortcuts if needed.')}
  return <Sheet open={open} onClose={onClose} title="Export this day" description="Take the selected day into the apps you already use.">
    {message&&<p className="auth-message day-export-status small" role="status" aria-live="polite">{message}</p>}
    <article className="day-export-preview" aria-label="Day export preview"><div className="row-between"><div><p className="eyebrow">Selected day</p><h3>{value.title.replace('Dayframe — ','')}</h3></div><span className="badge">{value.items.length} item{value.items.length===1?'':'s'}</span></div>{empty?<p className="muted small">Nothing is scheduled yet. Add work to this date before exporting.</p>:<div className="day-export-sections">{(['Train','Study','Travel']as DayExportCategory[]).map((category)=>{const items=value.items.filter((item)=>item.category===category);return items.length?<section key={category}><strong>{category}</strong>{items.map((item)=><div className="day-export-item" key={item.id}><span><Check size={13}/></span><div><b>{item.title}</b>{item.detail&&<small>{item.detail}</small>}</div></div>)}</section>:null})}</div>}</article>
    <div className="day-export-actions section">
      <button className="day-export-action" disabled={empty||busy} onClick={()=>void runShortcut()}><span className="icon-bubble"><Bell size={19}/></span><span><strong>Add to Apple Reminders</strong><small>{shortcutReady?'Separate dated reminders through your Shortcut':'One-time Shortcut setup required'}</small></span><ExternalLink size={16}/></button>
      <button className="day-export-action" disabled={empty||busy} onClick={()=>void share('notes')}><span className="icon-bubble"><NotebookPen size={19}/></span><span><strong>Save to Apple Notes</strong><small>Choose Notes and a folder in the Apple share sheet</small></span><Share2 size={16}/></button>
      <button className="day-export-action" disabled={empty||busy} onClick={()=>void copy()}><span className="icon-bubble"><Clipboard size={19}/></span><span><strong>Copy checklist</strong><small>Works on every device and notes app</small></span><Clipboard size={16}/></button>
    </div>
    {shortcutReady&&<section className="shortcut-management" aria-label="Apple Shortcut management"><div><strong>Apple Shortcut connected</strong><small>{shortcutName} · configured on this device</small></div><div className="row"><button className="link-button small" onClick={()=>{setShowSetup((value)=>!value);setConfirmReset(false)}}>{showSetup?'Hide steps':'View setup steps'}</button><button className="link-button small danger-link" onClick={()=>setConfirmReset(true)}>Reset Shortcut</button></div></section>}
    {confirmReset&&<section className="export-reset-confirm"><strong>Reset Shortcut setup?</strong><p className="muted small">This clears Dayframe’s setup and export warnings. It does not delete the Shortcut from Apple’s Shortcuts app.</p><div className="row"><button className="btn btn-secondary btn-small" onClick={resetShortcut}>Reset and show steps</button><button className="btn btn-ghost btn-small" onClick={()=>setConfirmReset(false)}>Cancel</button></div></section>}
    {exportedBefore&&!showSetup&&<p className="export-notice small">This date was already handed to the Shortcut on this device. Export again only if you intend to create another copy.</p>}
    {showSetup&&<ShortcutSetup onReady={()=>{localStorage.setItem('dayframe_reminders_shortcut_ready','true');setShortcutReady(true);setShowSetup(false);setMessage('Shortcut marked ready. Tap Add to Apple Reminders again.')}} onShare={()=>void share('reminders')}/>}
  </Sheet>
}

function ShortcutSetup({onReady,onShare}:{onReady:()=>void;onShare:()=>void}){
  const openShortcuts=()=>{window.location.href='shortcuts://create-shortcut'}
  return <article className="card card-pad shortcut-setup section"><p className="eyebrow">Set up or recreate</p><h3>Create “{shortcutName}”</h3><p className="muted small">This turns one Dayframe export into separate, dated Apple reminders. If you are recreating it, first delete or rename the old shortcut in Apple Shortcuts.</p><ol className="shortcut-steps"><li>Open Shortcuts, tap <strong>+</strong>, and use the exact name <strong>{shortcutName}</strong>.</li><li>Add <strong>Get Dictionary from Input</strong>.</li><li>Add <strong>Get Dictionary Value</strong>, enter <strong>items</strong>, then add <strong>Repeat with Each</strong>.</li><li>Inside the repeat block, get <strong>title</strong>, <strong>notes</strong> and <strong>dueAt</strong> from the Repeat Item. Add <strong>Get Dates from Input</strong> for dueAt.</li><li>Add <strong>New Reminder</strong> inside the repeat block. Set its title, notes and alert date from those values; select a Dayframe list or <strong>Ask Each Time</strong>.</li><li>Save and run it once. Tap <strong>Allow</strong> when Apple asks for Reminders access.</li></ol><div className="row progressive-actions"><button className="btn btn-primary" onClick={openShortcuts}><ExternalLink size={16}/>Open Shortcuts</button><button className="btn btn-secondary" onClick={onReady}>I’ve created it</button></div><button className="link-button small" onClick={onShare}>Skip setup and share one day-summary reminder</button></article>
}

async function copyText(text:string){
  if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return}
  const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();const copied=document.execCommand('copy');area.remove();if(!copied)throw new Error('Clipboard unavailable')
}
