import { useMemo, useState, type FormEvent } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { Activity, Bell, BookOpen, ChevronLeft, Dumbbell, Footprints, GlassWater, HeartPulse, Map, Moon, NotebookPen, Plus, Scale, Sparkles, Target, Utensils } from 'lucide-react'
import { Sheet } from './Sheet'
import { useData } from '../context/DataContext'
import { quickAddCategories } from '../lib/v2'

type Category=typeof quickAddCategories[number]
type ActionId='start_workout'|'walk'|'study_session'|'study_task'|'study_note'|'review'|'meal'|'summary'|'water'|'steps'|'sleep'|'weight'|'pain'|'reminder'|'goal'|'travel'|'life_note'
const actions:Record<Exclude<Category,'Recent'>,Array<{id:ActionId;label:string;icon:typeof Dumbbell}>>={
  Train:[{id:'start_workout',label:'Start workout',icon:Dumbbell},{id:'walk',label:'Walk',icon:Footprints}],
  Study:[{id:'study_session',label:'Study session',icon:BookOpen},{id:'study_task',label:'Problem / task',icon:Target},{id:'study_note',label:'Study note',icon:NotebookPen},{id:'review',label:'Review',icon:Sparkles}],
  Health:[{id:'meal',label:'Nutrition',icon:Utensils},{id:'water',label:'Water',icon:GlassWater},{id:'steps',label:'Steps',icon:Activity},{id:'sleep',label:'Sleep',icon:Moon},{id:'weight',label:'Bodyweight',icon:Scale},{id:'pain',label:'Pain',icon:HeartPulse}],
  Life:[{id:'reminder',label:'Reminder',icon:Bell},{id:'goal',label:'Goal',icon:Target},{id:'travel',label:'Travel',icon:Map},{id:'life_note',label:'Note',icon:NotebookPen}],
}
const byId=Object.values(actions).flat().reduce<Record<string,{id:ActionId;label:string;icon:typeof Dumbbell}>>((all,item)=>({...all,[item.id]:item}),{})

export function QuickAdd({open,onClose,onSaved}:{open:boolean;onClose:()=>void;onSaved:(message:string)=>void}){const[category,setCategory]=useState<Category|null>(null);const[selected,setSelected]=useState<ActionId|null>(null);const data=useData();const navigate=useNavigate();const location=useLocation();const recent=useMemo(()=>{if(!open)return[];try{return(JSON.parse(localStorage.getItem('dayframe_recent_actions')??'[]')as ActionId[]).filter((id)=>byId[id]).slice(0,4)}catch{return[]}},[open]);const ordered=useMemo(()=>{const context=location.pathname.startsWith('/train')?'Train':location.pathname.startsWith('/study')?'Study':location.pathname.startsWith('/life')?'Life':'Health';return[context,...quickAddCategories.filter((item)=>item!==context)]as Category[]},[location.pathname]);const close=()=>{setCategory(null);setSelected(null);onClose()};const remember=(id:ActionId)=>{localStorage.setItem('dayframe_recent_actions',JSON.stringify([id,...recent.filter((item)=>item!==id)].slice(0,4)))}
  const choose=(id:ActionId)=>{if(['start_workout'].includes(id)){close();navigate('/train');return}if(['study_session','study_task','study_note','review'].includes(id)){close();navigate('/study');return}if(id==='meal'||id==='summary'){close();navigate('/nutrition');return}if(id==='travel'||id==='life_note'){close();navigate('/life');return}setSelected(id)}
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget);const n=Number(f.get('amount')??0);if(selected==='walk')data.updateDaily({walkingMinutes:data.daily.walkingMinutes+n});if(selected==='water')data.updateDaily({waterMl:data.daily.waterMl+n});if(selected==='steps')data.updateDaily({steps:n});if(selected==='sleep')data.updateDaily({sleepHours:n,sleepQuality:Number(f.get('quality'))});if(selected==='weight')data.updateDaily({weight:n});if(selected==='pain')data.updateDaily({pain:{score:n,location:String(f.get('location')),note:String(f.get('note')??'')}});if(selected==='reminder')data.addReminder(String(f.get('title')),String(f.get('time')??''));if(selected==='goal')data.addGoal(String(f.get('title')),'Personal');remember(selected);onSaved(`${byId[selected].label} saved${navigator.onLine?'':' to offline queue'}`);close()}
  const title=selected?byId[selected].label:category??'Quick add';return <Sheet open={open} onClose={close} title={title} description={selected?'Saved to the selected day or durable offline queue.':category?'Choose one focused action.':'Recent actions and four clear domains.'}>{!category&&!selected&&<div className="quick-sections">{recent.length>0&&<div><p className="eyebrow">Recent</p><div className="quick-grid compact">{recent.map((id)=><QuickButton key={id} item={byId[id]} onClick={()=>choose(id)}/>)}</div></div>}<div><p className="eyebrow">Categories</p><div className="quick-grid categories">{ordered.filter((item)=>item!=='Recent').map((item)=><button className="quick-item" key={item} onClick={()=>setCategory(item)}><CategoryIcon name={item}/><strong>{item}</strong></button>)}</div></div></div>}{category&&!selected&&<><button className="btn btn-ghost btn-small" onClick={()=>setCategory(null)}><ChevronLeft size={15}/>Categories</button><div className="quick-grid section">{actions[category as Exclude<Category,'Recent'>].map((item)=><QuickButton key={item.id} item={item} onClick={()=>choose(item.id)}/>)}</div></>}{selected&&<form className="form-grid" onSubmit={submit}><button className="btn btn-ghost btn-small" type="button" onClick={()=>setSelected(null)}><ChevronLeft size={15}/>{category}</button>{(selected==='walk'||selected==='water'||selected==='steps'||selected==='weight')&&<NumberField label={selected==='walk'?'Minutes':selected==='water'?'Millilitres':selected==='steps'?'Step count':'Weight (kg)'} defaultValue={selected==='water'?'350':selected==='walk'?'20':''}/>} {selected==='sleep'&&<><NumberField label="Hours" step="0.1" defaultValue="7.5"/><label className="field"><span>Quality (1–5)</span><input className="input" name="quality" type="number" min="1" max="5" defaultValue="4" required/></label></>}{selected==='pain'&&<><NumberField label="Score (0–10)" min="0" max="10" defaultValue="2"/><label className="field"><span>Location</span><input className="input" name="location" required/></label><label className="field"><span>Note (optional)</span><textarea className="textarea" name="note"/></label></>}{(selected==='reminder'||selected==='goal')&&<label className="field"><span>Title</span><input className="input" name="title" required/></label>}{selected==='reminder'&&<label className="field"><span>Time</span><input className="input" name="time" type="time"/></label>}<button className="btn btn-primary"><Plus size={16}/>Save</button></form>}</Sheet>}
function QuickButton({item,onClick}:{item:{id:ActionId;label:string;icon:typeof Dumbbell};onClick:()=>void}){const Icon=item.icon;return <button className="quick-item" onClick={onClick}><Icon size={20}/><span>{item.label}</span></button>}
function CategoryIcon({name}:{name:string}){return name==='Train'?<Dumbbell/>:name==='Study'?<BookOpen/>:name==='Health'?<HeartPulse/>:<Sparkles/>}
function NumberField({label,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label className="field"><span>{label}</span><input className="input" name="amount" type="number" required {...props}/></label>}
